*CREATING LIBRARY;

%let path1 = C:\Users\panyue\Box\Yue Pan from old laptop 2015\DR FEASTER\Other Professors\111 STAR\STAR Data\DATA;
%let path2 = C:\Users\panyue\Box\Yue Pan from old laptop 2015\DR FEASTER\Other Professors\111 STAR\STAR Data\R012_06Mar23\Form Files\;

libname STAR "&path1.";

*CHANGE FILE PATH TO YOUR FORM FILES LOCATION;
%macro import(form=);
DATA STAR.&form;
INFILE "&path2.\data\&form..dat" TRUNCOVER LRECL = 5000;
%INCLUDE "&path2.\Codebooks\&form..inp";
%INCLUDE "&path2.\Codebooks\&form..lbl";
%INCLUDE "&path2.\Codebooks\&form..fmt";
run;
%mend;

%import (form=stel);		%import (form=stasc);		%import (form=staer);		%import (form=stascs1);
%import (form=stascs2);		%import (form=stascs3);		%import (form=stascs4);		%import (form=stblbeh);
%import (form=stblcovid);	%import (form=stblhcu);		%import (form=stblhh);		%import (form=stblhha);
%import (form=stblhhas1);	%import (form=stblhhas2);	%import (form=stblhhs1);	%import (form=stblhhs2);
%import (form=stblhhs3);	%import (form=stblhhs4);	%import (form=stblhhs5);	%import (form=stblhhs6);
%import (form=stblhhs7);	%import (form=stblhhs9);	%import (form=stblhhs10);	%import (form=stblhosp);
%import (form=stblhosps1);	%import (form=stblhpv);		%import (form=stblob);		%import (form=stblobs1);
%import (form=stblobs2);	%import (form=stblobs3);	%import (form=stblobs4);	%import (form=stblobs5);
%import (form=stblobs6);	%import (form=stblobs7);	%import (form=stbloral);	%import (form=stblsd);
%import (form=stblsds1);	%import (form=stco);		%import (form=stcons);		%import (form=stcont);
%import (form=stcovid);		%import (form=stcovids1);	%import (form=stcovids2);	%import (form=stdenr);		
%import (form=sthpvab);		%import (form=stlab);		%import (form=stpe);		%import (form=stprasc);		
%import (form=stprascs1);	%import (form=stprascs2);	%import (form=stprascs3);	%import (form=stprhh);		
%import (form=stprr);		%import (form=strab);		%import (form=strabs1);		%import (form=strabs2);		
%import (form=strsp);		%import (form=stsc);

*ADDING FORMATS;
%macro data(form=);
data STAR.&form;
set STAR.&form;
%mend;

%data (form=staer);
   FORMAT  SITE SITEf. ;
   FORMAT  ERSVSAE ERSVSAEf. ;
   FORMAT  EVAPSAE EVAPSAEf. ;
   FORMAT  ERPISAE ERPISAEf. ;
   FORMAT  STRGSAE STRGSAEf. ;
   FORMAT  RPRTSAE RPRTSAEf. ;
run;

%data (form=stasc);
	FORMAT  SITE SITEf. ;
   FORMAT  RFCMPSOA RFCMPSOAf. ;
   FORMAT  HIVSSOA HIVSSOAf. ;
   FORMAT  HTCASOA HTCASOAf. ;
   FORMAT  HRNARSOA HRNARSOAf. ;
   FORMAT  HRBLDSOA HRBLDSOAf. ;
   FORMAT  TCELRSOA TCELRSOAf. ;
   FORMAT  PRPAPSOA PRPAPSOAf. ;
   FORMAT  PAPPSSOA PAPPSSOAf. ;
   FORMAT  PAPRRSOA PAPRRSOAf. ;
   FORMAT  RPRNRSOA RPRNRSOAf. ;
   FORMAT  PRCORSOA PRCORSOAf. ;
   FORMAT  PSADQSOA PSADQSOAf. ;
   FORMAT  PAPDXSOA PAPDXSOAf. ;
   FORMAT  AFPAPSOA AFPAPSOAf. ;
   FORMAT  PAFASSOA PAFASSOAf. ;
   FORMAT  PAFECSOA PAFECSOAf. ;
   FORMAT  PAFSDSOA PAFSDSOAf. ;
   FORMAT  PAFSTSOA PAFSTSOAf. ;
   FORMAT  PAFSBSOA PAFSBSOAf. ;
   FORMAT  PAFCASOA PAFCASOAf. ;
   FORMAT  PAFOTSOA PAFOTSOAf. ;
   FORMAT  PRHPVSOA PRHPVSOAf. ;
   FORMAT  HPVPSSOA HPVPSSOAf. ;
   FORMAT  HPVRRSOA HPVRRSOAf. ;
   FORMAT  RHRNRSOA RHRNRSOAf. ;
   FORMAT  HRCORSOA HRCORSOAf. ;
   FORMAT  HPVROHSOA HPVROHSOAf. ;
   FORMAT  HPVR16SOA HPVR16SOAf. ;
   FORMAT  HPVR18SOA HPVR18SOAf. ;
   FORMAT  PRCDYSOA PRCDYSOAf. ;
   FORMAT  CDYPSSOA CDYPSSOAf. ;
   FORMAT  PRCANSOA PRCANSOAf. ;
   FORMAT  CANPSSOA CANPSSOAf. ;
   FORMAT  PRTBDSOA PRTBDSOAf. ;
   FORMAT  TBDPSSOA TBDPSSOAf. ;
   FORMAT  TBDRRSOA TBDRRSOAf. ;
   FORMAT  RTRNRSOA RTRNRSOAf. ;
   FORMAT  TBCORSOA TBCORSOAf. ;
   FORMAT  TMCYSSOA TMCYSSOAf. ;
   FORMAT  TMCLTSOA TMCLTSOAf. ;
   FORMAT  TMSERSOA TMSERSOAf. ;
   FORMAT  TMCDXSOA TMCDXSOAf. ;
   FORMAT  TMRADSOA TMRADSOAf. ;
   FORMAT  TMNCRSOA TMNCRSOAf. ;
   FORMAT  TMRDCSOA TMRDCSOAf. ;
   FORMAT  TMUODSOA TMUODSOAf. ;
   FORMAT  TDCLVSOA TDCLVSOAf. ;
   FORMAT  PDECSOA PDECSOAf. ;
   FORMAT  SDFAMSOA SDFAMSOAf. ;
   FORMAT  SDHSPSOA SDHSPSOAf. ;
   FORMAT  SDDCSSOA SDDCSSOAf. ;
   FORMAT  SDOBISOA SDOBISOAf. ;
   FORMAT  SDRHCSOA SDRHCSOAf. ;
   FORMAT  SDASVSOA SDASVSOAf. ;
   FORMAT  SDOTHSOA SDOTHSOAf. ;
   FORMAT  PODSOA PODSOAf. ;
   FORMAT  MODSOA MODSOAf. ;
   FORMAT  DTHRRSOA DTHRRSOAf. ;
   FORMAT  RDRNRSOA RDRNRSOAf. ;
   FORMAT  AUTPSOA AUTPSOAf. ;
run;

%data (form=stasc1);
   FORMAT  CDYRRSOA CDYRRSOAf. ;
   FORMAT  RCRNRSOA RCRNRSOAf. ;
   FORMAT  CRCORSOA CRCORSOAf. ;
   FORMAT  TMINTSOA TMINTSOAf. ;
   FORMAT  TM5FUSOA TM5FUSOAf. ;
   FORMAT  TMCRYSOA TMCRYSOAf. ;
   FORMAT  TMLSVSOA TMLSVSOAf. ;
   FORMAT  TMLSCSOA TMLSCSOAf. ;
   FORMAT  TMLTZSOA TMLTZSOAf. ;
   FORMAT  TMLCNSOA TMLCNSOAf. ;
   FORMAT  TMCKCSOA TMCKCSOAf. ;
   FORMAT  TMHYSSOA TMHYSSOAf. ;
   FORMAT  TMHYRSOA TMHYRSOAf. ;
   FORMAT  TMRADSOA TMRADSOAf. ;
   FORMAT  TMOTHSOA TMOTHSOAf. ;
   FORMAT  INDCTSOA INDCTSOAf. ;

run;

%data (form=stasc2);
   FORMAT  CANRRSOA CANRRSOAf. ;
   FORMAT  RCNRNRSOA RCNRNRSOAf. ;
   FORMAT  CNRCORSOA CNRCORSOAf. ;
   FORMAT  TTUMRSOA TTUMRSOAf. ;
   FORMAT  CMHABSOA CMHABSOAf. ;
   FORMAT  CMNECSOA CMNECSOAf. ;
   FORMAT  CMCYSSOA CMCYSSOAf. ;
   FORMAT  CMCLTSOA CMCLTSOAf. ;
   FORMAT  CMSERSOA CMSERSOAf. ;
   FORMAT  CMCDXSOA CMCDXSOAf. ;
   FORMAT  CMRADSOA CMRADSOAf. ;
   FORMAT  CMNCRSOA CMNCRSOAf. ;
   FORMAT  CMRDCSOA CMRDCSOAf. ;
   FORMAT  CMUODSOA CMUODSOAf. ;
   FORMAT  CDCLVSOA CDCLVSOAf. ;

run;

%data (form=stasc3);
run;

%data (form=stasc4);
run;

%data (form=stblbeh);
   FORMAT  SITE SITEf. ;
   FORMAT  HIVSSBE HIVSSBEf. ;
   FORMAT  MVCDSBE MVCDSBEf. ;
   FORMAT  MACDSBE MACDSBEf. ;
   FORMAT  EVSXPDSBE EVSXPDSBEf. ;
   FORMAT  SXDRSBE SXDRSBEf. ;
   FORMAT  EVALCSBE EVALCSBEf. ;
   FORMAT  FDRKSBE FDRKSBEf. ;
   FORMAT  NMDDSBE NMDDSBEf. ;
   FORMAT  FDR5SBE FDR5SBEf. ;
   FORMAT  FNSTPSBE FNSTPSBEf. ;
   FORMAT  FFTDESBE FFTDESBEf. ;
   FORMAT  FDMRNSBE FDMRNSBEf. ;
   FORMAT  FGFGLTSBE FGFGLTSBEf. ;
   FORMAT  FRMBRSBE FRMBRSBEf. ;
   FORMAT  INJRDSBE INJRDSBEf. ;
   FORMAT  CNCRDSBE CNCRDSBEf. ;
   FORMAT  EVDMALSBE EVDMALSBEf. ;
   FORMAT  DMDPWASBE DMDPWASBEf. ;
   FORMAT  DMNUMDSBE DMNUMDSBEf. ;
   FORMAT  EVEATXSBE EVEATXSBEf. ;
   FORMAT  EVINADSBE EVINADSBEf. ;
   FORMAT  EVOUTPSBE EVOUTPSBEf. ;
   FORMAT  EVHLFASBE EVHLFASBEf. ;
   FORMAT  EVINAASBE EVINAASBEf. ;
   FORMAT  EVOPRGSBE EVOPRGSBEf. ;
   FORMAT  EVPOTSBE EVPOTSBEf. ;
   FORMAT  POTUSBE POTUSBEf. ;
   FORMAT  RPOTRSSBE RPOTRSSBEf. ;
   FORMAT  RPOTSSSBE RPOTSSSBEf. ;
   FORMAT  RPOTHSSBE RPOTHSSBEf. ;
   FORMAT  RPOTAPSBE RPOTAPSBEf. ;
   FORMAT  RPOTEDSBE RPOTEDSBEf. ;
   FORMAT  RPOTOTSBE RPOTOTSBEf. ;
   FORMAT  HMSMSBE HMSMSBEf. ;
   FORMAT  HMVPSBE HMVPSBEf. ;
   FORMAT  HMETSBE HMETSBEf. ;
   FORMAT  HMOTSBE HMOTSBEf. ;
   FORMAT  EVPOPSBE EVPOPSBEf. ;
   FORMAT  POPUSBE POPUSBEf. ;
   FORMAT  EVSMCRSBE EVSMCRSBEf. ;
   FORMAT  SCRFSBE SCRFSBEf. ;
   FORMAT  EVCOCSBE EVCOCSBEf. ;
   FORMAT  COCUSBE COCUSBEf. ;
   FORMAT  COCIJSBE COCIJSBEf. ;
   FORMAT  COCSMSBE COCSMSBEf. ;
   FORMAT  COCSNSBE COCSNSBEf. ;
   FORMAT  EVSMISBE EVSMISBEf. ;
   FORMAT  SMIUSBE SMIUSBEf. ;
   FORMAT  SMIIJSBE SMIIJSBEf. ;
   FORMAT  SMISMSBE SMISMSBEf. ;
   FORMAT  SMISNSBE SMISNSBEf. ;
   FORMAT  EVHERSBE EVHERSBEf. ;
   FORMAT  HERUSBE HERUSBEf. ;
   FORMAT  IHERSBE IHERSBEf. ;
   FORMAT  HESMSBE HESMSBEf. ;
   FORMAT  HESNSBE HESNSBEf. ;
   FORMAT  EVSPBLSBE EVSPBLSBEf. ;
   FORMAT  SPBFSBE SPBFSBEf. ;
   FORMAT  EVBZBASBE EVBZBASBEf. ;
   FORMAT  BZBAUSBE BZBAUSBEf. ;
   FORMAT  EVHALKSBE EVHALKSBEf. ;
   FORMAT  HALKUSBE HALKUSBEf. ;
   FORMAT  EVOIRDSBE EVOIRDSBEf. ;
   FORMAT  OVDESBE OVDESBEf. ;
   FORMAT  ODEVSBE ODEVSBEf. ;
   FORMAT  NRCSVSBE NRCSVSBEf. ;
   FORMAT  EVEDTXSBE EVEDTXSBEf. ;
   FORMAT  EVINDDSBE EVINDDSBEf. ;
   FORMAT  EVOUTDSBE EVOUTDSBEf. ;
   FORMAT  EVMEMPSBE EVMEMPSBEf. ;
   FORMAT  EVHLFDSBE EVHLFDSBEf. ;
   FORMAT  EVINNASBE EVINNASBEf. ;
   FORMAT  EVJAILSBE EVJAILSBEf. ;
   FORMAT  EVODRGSBE EVODRGSBEf. ;
   FORMAT  MDTXSBE MDTXSBEf. ;
   FORMAT  MDTXMTSBE MDTXMTSBEf. ;
   FORMAT  MDTXNXSBE MDTXNXSBEf. ;
   FORMAT  MDTXSXSBE MDTXSXSBEf. ;
   FORMAT  FCSMSBE FCSMSBEf. ;
   FORMAT  QPAKSBE QPAKSBEf. ;
   FORMAT  SMOKSBE SMOKSBEf. ;
   FORMAT  CIGCUSBE CIGCUSBEf. ;
   FORMAT  CIGPKSBE CIGPKSBEf. ;
   FORMAT  CPAKSBE CPAKSBEf. ;
   FORMAT  EVECIGSBE EVECIGSBEf. ;
   FORMAT  ECFQSBE ECFQSBEf. ;
   FORMAT  ECNWSBE ECNWSBEf. ;
   FORMAT  ECQSSBE ECQSSBEf. ;
   FORMAT  ECCDSBE ECCDSBEf. ;
   FORMAT  ECNASBE ECNASBEf. ;
   FORMAT  ECAVSBE ECAVSBEf. ;
   FORMAT  ECEJSBE ECEJSBEf. ;
   FORMAT  ECTRSBE ECTRSBEf. ;
   FORMAT  ECORSBE ECORSBEf. ;
   FORMAT  BTHRSBE BTHRSBEf. ;
   FORMAT  NOAPSBE NOAPSBEf. ;
   FORMAT  WBLUSBE WBLUSBEf. ;
   FORMAT  GOODSBE GOODSBEf. ;
   FORMAT  CONCSBE CONCSBEf. ;
   FORMAT  DEPRSBE DEPRSBEf. ;
   FORMAT  EFFTSBE EFFTSBEf. ;
   FORMAT  FUTRSBE FUTRSBEf. ;
   FORMAT  FAILSBE FAILSBEf. ;
   FORMAT  FEARSBE FEARSBEf. ;
   FORMAT  SLEPSBE SLEPSBEf. ;
   FORMAT  WHPYSBE WHPYSBEf. ;
   FORMAT  TALKSBE TALKSBEf. ;
   FORMAT  LONESBE LONESBEf. ;
   FORMAT  UNFRSBE UNFRSBEf. ;
   FORMAT  ENJYSBE ENJYSBEf. ;
   FORMAT  CRY_SBE CRY_SBEf. ;
   FORMAT  SAD_SBE SAD_SBEf. ;
   FORMAT  DISLSBE DISLSBEf. ;
   FORMAT  MOTVSBE MOTVSBEf. ;
   FORMAT  LCMPSBE LCMPSBEf. ;
   FORMAT  LOUTSBE LOUTSBEf. ;
   FORMAT  ISOLSBE ISOLSBEf. ;
   FORMAT  SSACBSBE SSACBSBEf. ;
   FORMAT  SSADCSBE SSADCSBEf. ;
   FORMAT  SSAPMSBE SSAPMSBEf. ;
   FORMAT  SSACHSBE SSACHSBEf. ;
   FORMAT  SSAGTSBE SSAGTSBEf. ;
   FORMAT  SSAPPSBE SSAPPSBEf. ;
   FORMAT  SSAUPSBE SSAUPSBEf. ;
   FORMAT  SSALVSBE SSALVSBEf. ;
   FORMAT  UNEXSBE UNEXSBEf. ;
   FORMAT  UCTLSBE UCTLSBEf. ;
   FORMAT  NERVSBE NERVSBEf. ;
   FORMAT  CONFSBE CONFSBEf. ;
   FORMAT  YWAYSBE YWAYSBEf. ;
   FORMAT  COPESBE COPESBEf. ;
   FORMAT  CTRLSBE CTRLSBEf. ;
   FORMAT  OTOPSBE OTOPSBEf. ;
   FORMAT  ANGRSBE ANGRSBEf. ;
   FORMAT  DIFFSBE DIFFSBEf. ;
   FORMAT  HLTHSBE HLTHSBEf. ;
   FORMAT  VACTSBE VACTSBEf. ;
   FORMAT  MACTSBE MACTSBEf. ;
   FORMAT  STRSSBE STRSSBEf. ;
   FORMAT  HLBLSSBE HLBLSSBEf. ;
   FORMAT  HLW1BSBE HLW1BSBEf. ;
   FORMAT  DRSSSBE DRSSSBEf. ;
   FORMAT  PAINSBE PAINSBEf. ;
   FORMAT  HLJOBSBE HLJOBSBEf. ;
   FORMAT  HWRKSBE HWRKSBEf. ;
   FORMAT  SOCASBE SOCASBEf. ;
   FORMAT  NERV4SBE NERV4SBEf. ;
   FORMAT  CALMSBE CALMSBEf. ;
   FORMAT  BLUESBE BLUESBEf. ;
   FORMAT  HAPYSBE HAPYSBEf. ;
   FORMAT  CHEERSBE CHEERSBEf. ;
   FORMAT  SILLSBE SILLSBEf. ;
   FORMAT  HLABSBE HLABSBEf. ;
   FORMAT  HEXCSBE HEXCSBEf. ;
   FORMAT  FBADSBE FBADSBEf. ;
   FORMAT  AGETWOSBE AGETWOSBEf. ;
   FORMAT  APEPLYSBE APEPLYSBEf. ;
   FORMAT  AOLUSESBE AOLUSESBEf. ;
   FORMAT  ABETWRSBE ABETWRSBEf. ;
   FORMAT  AHAPYNSBE AHAPYNSBEf. ;
   FORMAT  RBNCHTSBE RBNCHTSBEf. ;
   FORMAT  RHTSTRSBE RHTSTRSBEf. ;
   FORMAT  RRCSTRSBE RRCSTRSBEf. ;
   FORMAT  RSNPBKSBE RSNPBKSBEf. ;
   FORMAT  RCTHRUSBE RCTHRUSBEf. ;
   FORMAT  RSTBCKSBE RSTBCKSBEf. ;
   FORMAT  CNDCMSBE CNDCMSBEf. ;
   FORMAT  CFLFLSBE CFLFLSBEf. ;
   FORMAT  CMEMNSBE CMEMNSBEf. ;
   FORMAT  CBLNGSBE CBLNGSBEf. ;
   FORMAT  CSAYGSBE CSAYGSBEf. ;
   FORMAT  CINFLSBE CINFLSBEf. ;
   FORMAT  CCNCTSBE CCNCTSBEf. ;
   FORMAT  CBONDSBE CBONDSBEf. ;
   FORMAT  SFSWLKSBE SFSWLKSBEf. ;
   FORMAT  SFVLNCSBE SFVLNCSBEf. ;
   FORMAT  SFCRIMSBE SFCRIMSBEf. ;
   FORMAT  SFWPONSBE SFWPONSBEf. ;
   FORMAT  SFGANGSBE SFGANGSBEf. ;
   FORMAT  SFRAPESBE SFRAPESBEf. ;
   FORMAT  SFROBSBE SFROBSBEf. ;
   FORMAT  SFGUNSSBE SFGUNSSBEf. ;
   FORMAT  UHAUUSBE UHAUUSBEf. ;
   FORMAT  UHPFMCSBE UHPFMCSBEf. ;
   FORMAT  UHPFUDSBE UHPFUDSBEf. ;
   FORMAT  UHNFMCSBE UHNFMCSBEf. ;
   FORMAT  UHNFUASBE UHNFUASBEf. ;
run;

%data (form=stblcovid);
   FORMAT  SITE SITEf. ;
   FORMAT  TPOSSCV TPOSSCVf. ;
   FORMAT  CSYMPSCV CSYMPSCVf. ;
   FORMAT  SPACTSCV SPACTSCVf. ;
   FORMAT  HOSPCSCV HOSPCSCVf. ;
   FORMAT  IHOXYSCV IHOXYSCVf. ;
   FORMAT  IHVNTSCV IHVNTSCVf. ;
   FORMAT  IHICUSCV IHICUSCVf. ;
   FORMAT  IHDIASCV IHDIASCVf. ;
   FORMAT  RECVRSCV RECVRSCVf. ;
   FORMAT  HBMAWSCV HBMAWSCVf. ;
   FORMAT  HBMOSSCV HBMOSSCVf. ;
   FORMAT  HFATGSCV HFATGSCVf. ;
   FORMAT  HHDACSCV HHDACSCVf. ;
   FORMAT  HLSMLSCV HLSMLSCVf. ;
   FORMAT  HLTSTSCV HLTSTSCVf. ;
   FORMAT  HVISNSCV HVISNSCVf. ;
   FORMAT  HSPCHSCV HSPCHSCVf. ;
   FORMAT  HNTNGSCV HNTNGSCVf. ;
   FORMAT  HNTOSSCV HNTOSSCVf. ;
   FORMAT  HTIVMSCV HTIVMSCVf. ;
   FORMAT  HBLNCSCV HBLNCSCVf. ;
   FORMAT  HDZYSCV HDZYSCVf. ;
   FORMAT  HMEMSCV HMEMSCVf. ;
   FORMAT  HBFOGSCV HBFOGSCVf. ;
   FORMAT  HAPPTSCV HAPPTSCVf. ;
   FORMAT  HMOODSCV HMOODSCVf. ;
   FORMAT  HINSMSCV HINSMSCVf. ;
   FORMAT  HHAIRSCV HHAIRSCVf. ;
   FORMAT  HSEIZSCV HSEIZSCVf. ;
   FORMAT  HOTHRSCV HOTHRSCVf. ;
   FORMAT  RVACSCV RVACSCVf. ;
   FORMAT  KNMEVSCV KNMEVSCVf. ;
   FORMAT  WVACSCV WVACSCVf. ;
   FORMAT  NSDSSCV NSDSSCVf. ;
   FORMAT  RSD_SCV RSD_SCVf. ;
   FORMAT  APTSDSCV APTSDSCVf. ;
run;

%data (form=stblhcu);
   FORMAT  SITE SITEf. ;
   FORMAT  HCP6SHC HCP6SHCf. ;
   FORMAT  SDOCSHC SDOCSHCf. ;
   FORMAT  CLINSHC CLINSHCf. ;
   FORMAT  MHP_SHC MHP_SHCf. ;
   FORMAT  HIVSSHC HIVSSHCf. ;
   FORMAT  RH6MSHC RH6MSHCf. ;
   FORMAT  ADSVSHC ADSVSHCf. ;
   FORMAT  MCRWSHC MCRWSHCf. ;
   FORMAT  MCSVSHC MCSVSHCf. ;
   FORMAT  MCEMSHC MCEMSHCf. ;
   FORMAT  CMCEMSHC CMCEMSHCf. ;
   FORMAT  NMCEMSHC NMCEMSHCf. ;
   FORMAT  MCINSHC MCINSHCf. ;
   FORMAT  CMCINSHC CMCINSHCf. ;
   FORMAT  NMCINSHC NMCINSHCf. ;
   FORMAT  MCEXSHC MCEXSHCf. ;
   FORMAT  MCSBSHC MCSBSHCf. ;
   FORMAT  MCMCSHC MCMCSHCf. ;
   FORMAT  CMCMCSHC CMCMCSHCf. ;
   FORMAT  NMCMCSHC NMCMCSHCf. ;
   FORMAT  MC65SHC MC65SHCf. ;
   FORMAT  CMC65SHC CMC65SHCf. ;
   FORMAT  NMC65SHC NMC65SHCf. ;
   FORMAT  MCVBSHC MCVBSHCf. ;
   FORMAT  CMCVBSHC CMCVBSHCf. ;
   FORMAT  NMCVBSHC NMCVBSHCf. ;
   FORMAT  MCDISHC MCDISHCf. ;
   FORMAT  CMCDISHC CMCDISHCf. ;
   FORMAT  NMCDISHC NMCDISHCf. ;
   FORMAT  MCOTSHC MCOTSHCf. ;
   FORMAT  CMCOTSHC CMCOTSHCf. ;
   FORMAT  NMCOTSHC NMCOTSHCf. ;
   FORMAT  MCMDSHC MCMDSHCf. ;
   FORMAT  NHITSHC NHITSHCf. ;
   FORMAT  NHIDSHC NHIDSHCf. ;
   FORMAT  RXPASHC RXPASHCf. ;
   FORMAT  OPMDSHC OPMDSHCf. ;
   FORMAT  OPRXSHC OPRXSHCf. ;
   FORMAT  OPHCSHC OPHCSHCf. ;
   FORMAT  MCNASHC MCNASHCf. ;
   FORMAT  MCDLSHC MCDLSHCf. ;
   FORMAT  DENTSHC DENTSHCf. ;
run;

%data (form=stblhh);
   FORMAT  SITE SITEf. ;
   FORMAT  BY__SMH BY__SMHf. ;
   FORMAT  BY_LSMH BY_LSMHf. ;
   FORMAT  LBXDRSMH LBXDRSMHf. ;
   FORMAT  BY_SSMH BY_SSMHf. ;
   FORMAT  SBXDRSMH SBXDRSMHf. ;
   FORMAT  BY_BSMH BY_BSMHf. ;
   FORMAT  MBXDRSMH MBXDRSMHf. ;
   FORMAT  BY_CSMH BY_CSMHf. ;
   FORMAT  CBXDRSMH CBXDRSMHf. ;
   FORMAT  BYUESMH BYUESMHf. ;
   FORMAT  UBXDRSMH UBXDRSMHf. ;
   FORMAT  BYBRSMH BYBRSMHf. ;
   FORMAT  BBXDRSMH BBXDRSMHf. ;
   FORMAT  BYLVSMH BYLVSMHf. ;
   FORMAT  LVBDRSMH LVBDRSMHf. ;
   FORMAT  BYGUTSMH BYGUTSMHf. ;
   FORMAT  GBXDRSMH GBXDRSMHf. ;
   FORMAT  BYANLSMH BYANLSMHf. ;
   FORMAT  ABXDRSMH ABXDRSMHf. ;
   FORMAT  BY_OSMH BY_OSMHf. ;
   FORMAT  OBXDRSMH OBXDRSMHf. ;
   FORMAT  CANCEVSMH CANCEVSMHf. ;
   FORMAT  CCXEVSMH CCXEVSMHf. ;
   FORMAT  CBCEVSMH CBCEVSMHf. ;
   FORMAT  COVEVSMH COVEVSMHf. ;
   FORMAT  CENEVSMH CENEVSMHf. ;
   FORMAT  CKSEVSMH CKSEVSMHf. ;
   FORMAT  CLYEVSMH CLYEVSMHf. ;
   FORMAT  CLBEVSMH CLBEVSMHf. ;
   FORMAT  CHOEVSMH CHOEVSMHf. ;
   FORMAT  CSKEVSMH CSKEVSMHf. ;
   FORMAT  CNLEVSMH CNLEVSMHf. ;
   FORMAT  CANEVSMH CANEVSMHf. ;
   FORMAT  CLUEVSMH CLUEVSMHf. ;
   FORMAT  CCOEVSMH CCOEVSMHf. ;
   FORMAT  COCEVSMH COCEVSMHf. ;
   FORMAT  HIVSSMH HIVSSMHf. ;
   FORMAT  CTAAMSMH CTAAMSMHf. ;
   FORMAT  OFFTXSMH OFFTXSMHf. ;
   FORMAT  OFAVSMH OFAVSMHf. ;
   FORMAT  MG30SMH MG30SMHf. ;
   FORMAT  MF30SMH MF30SMHf. ;
   FORMAT  VACISMH VACISMHf. ;
   FORMAT  HIVS2SMH HIVS2SMHf. ;
   FORMAT  ETPREPSMH ETPREPSMHf. ;
   FORMAT  TPREPSMH TPREPSMHf. ;
   FORMAT  PRCAUSMH PRCAUSMHf. ;
   FORMAT  PRCAHSMH PRCAHSMHf. ;
   FORMAT  PRCVUSMH PRCVUSMHf. ;
   FORMAT  PRCVHSMH PRCVHSMHf. ;
   FORMAT  PRBKCSMH PRBKCSMHf. ;
   FORMAT  PRIDUSMH PRIDUSMHf. ;
   FORMAT  PROTHSMH PROTHSMHf. ;
   FORMAT  CNSPRSMH CNSPRSMHf. ;
   FORMAT  STPPRSMH STPPRSMHf. ;
   FORMAT  SPRSESMH SPRSESMHf. ;
   FORMAT  SPRTESMH SPRTESMHf. ;
   FORMAT  SPRDFSMH SPRDFSMHf. ;
   FORMAT  SPRNRSMH SPRNRSMHf. ;
   FORMAT  SPRUPSMH SPRUPSMHf. ;
   FORMAT  SPRFISMH SPRFISMHf. ;
   FORMAT  SPROTSMH SPROTSMHf. ;
   FORMAT  WPREPSMH WPREPSMHf. ;
   FORMAT  UOCPRSMH UOCPRSMHf. ;
   FORMAT  NOPPRSMH NOPPRSMHf. ;
   FORMAT  ETKPEPSMH ETKPEPSMHf. ;
   FORMAT  PECAUSMH PECAUSMHf. ;
   FORMAT  PECAHSMH PECAHSMHf. ;
   FORMAT  PECVUSMH PECVUSMHf. ;
   FORMAT  PECVHSMH PECVHSMHf. ;
   FORMAT  PEBKCSMH PEBKCSMHf. ;
   FORMAT  PECIMSMH PECIMSMHf. ;
   FORMAT  PEIDUSMH PEIDUSMHf. ;
   FORMAT  PEOTHSMH PEOTHSMHf. ;
   FORMAT  EHEPATSMH EHEPATSMHf. ;
   FORMAT  EHEPTASMH EHEPTASMHf. ;
   FORMAT  EHEPTBSMH EHEPTBSMHf. ;
   FORMAT  EHEPCSMH EHEPCSMHf. ;
   FORMAT  EHEPOTSMH EHEPOTSMHf. ;
   FORMAT  EHEPDKSMH EHEPDKSMHf. ;
   FORMAT  PRHBDSMH PRHBDSMHf. ;
   FORMAT  EHEPBMSMH EHEPBMSMHf. ;
   FORMAT  PRHCDSMH PRHCDSMHf. ;
   FORMAT  EHCGT1SMH EHCGT1SMHf. ;
   FORMAT  TMHPCSMH TMHPCSMHf. ;
   FORMAT  ELFIBSMH ELFIBSMHf. ;
   FORMAT  LDCRSMH LDCRSMHf. ;
   FORMAT  LDASSMH LDASSMHf. ;
   FORMAT  LDVRSMH LDVRSMHf. ;
   FORMAT  LDHESMH LDHESMHf. ;
   FORMAT  ETLTSMH ETLTSMHf. ;
   FORMAT  EHLTSMH EHLTSMHf. ;
   FORMAT  WLLTSMH WLLTSMHf. ;
   FORMAT  EHAVSMH EHAVSMHf. ;
   FORMAT  EHBVSMH EHBVSMHf. ;
   FORMAT  EFLUVSMH EFLUVSMHf. ;
   FORMAT  EHPVVSMH EHPVVSMHf. ;
   FORMAT  EPNVSMH EPNVSMHf. ;
   FORMAT  EVAVSMH EVAVSMHf. ;
   FORMAT  ETEVSMH ETEVSMHf. ;
   FORMAT  ESHNVSMH ESHNVSMHf. ;
   FORMAT  EMENVSMH EMENVSMHf. ;
   FORMAT  EPREGSMH EPREGSMHf. ;
   FORMAT  PDIASMH PDIASMHf. ;
   FORMAT  PHBPSMH PHBPSMHf. ;
   FORMAT  PDPRSMH PDPRSMHf. ;
   FORMAT  PANXSMH PANXSMHf. ;
   FORMAT  POHPSMH POHPSMHf. ;
   FORMAT  EPNEUMSMH EPNEUMSMHf. ;
   FORMAT  EPNHSPSMH EPNHSPSMHf. ;
   FORMAT  EHBCLSMH EHBCLSMHf. ;
   FORMAT  MCBSSMH MCBSSMHf. ;
   FORMAT  EHYTNSMH EHYTNSMHf. ;
   FORMAT  EVANSMH EVANSMHf. ;
   FORMAT  EHHDSSMH EHHDSSMHf. ;
   FORMAT  EVMISMH EVMISMHf. ;
   FORMAT  EVCFSMH EVCFSMHf. ;
   FORMAT  EHCHFSMH EHCHFSMHf. ;
   FORMAT  EVSTSMH EVSTSMHf. ;
   FORMAT  EVTISMH EVTISMHf. ;
   FORMAT  EBVBLKSMH EBVBLKSMHf. ;
   FORMAT  EVAFBSMH EVAFBSMHf. ;
   FORMAT  EVAFLSMH EVAFLSMHf. ;
   FORMAT  EHBPROSMH EHBPROSMHf. ;
   FORMAT  EHBANGSMH EHBANGSMHf. ;
   FORMAT  EHBCBSSMH EHBCBSSMHf. ;
   FORMAT  EHBCRDSMH EHBCRDSMHf. ;
   FORMAT  EHBABLSMH EHBABLSMHf. ;
   FORMAT  EHBSGVSMH EHBSGVSMHf. ;
   FORMAT  EHBSTVSMH EHBSTVSMHf. ;
   FORMAT  EHBSGCSMH EHBSGCSMHf. ;
   FORMAT  EHBSTCSMH EHBSTCSMHf. ;
   FORMAT  EHBSGLSMH EHBSGLSMHf. ;
   FORMAT  EHBSTLSMH EHBSTLSMHf. ;
   FORMAT  EHBSGASMH EHBSGASMHf. ;
   FORMAT  EHBSTASMH EHBSTASMHf. ;
   FORMAT  EHBOTHSMH EHBOTHSMHf. ;
   FORMAT  MCKPSMH MCKPSMHf. ;
   FORMAT  DIALSMH DIALSMHf. ;
   FORMAT  ECOPDSMH ECOPDSMHf. ;
   FORMAT  EHCOPDSMH EHCOPDSMHf. ;
   FORMAT  EUCOPDSMH EUCOPDSMHf. ;
   FORMAT  EASTHSMH EASTHSMHf. ;
   FORMAT  EHASTHSMH EHASTHSMHf. ;
   FORMAT  EUASTHSMH EUASTHSMHf. ;
   FORMAT  EPFBSMH EPFBSMHf. ;
   FORMAT  EPHYSMH EPHYSMHf. ;
   FORMAT  EPEMSMH EPEMSMHf. ;
   FORMAT  EDVTSMH EDVTSMHf. ;
   FORMAT  EPADPSMH EPADPSMHf. ;
   FORMAT  ELNGSMH ELNGSMHf. ;
   FORMAT  ESAPSMH ESAPSMHf. ;
   FORMAT  ESLPSSMH ESLPSSMHf. ;
   FORMAT  LDFLSMH LDFLSMHf. ;
   FORMAT  ESSPBPSMH ESSPBPSMHf. ;
   FORMAT  EDEPRSMH EDEPRSMHf. ;
   FORMAT  EDPRSMH EDPRSMHf. ;
   FORMAT  EANXSMH EANXSMHf. ;
   FORMAT  ESCHZSMH ESCHZSMHf. ;
   FORMAT  EPTSDSMH EPTSDSMHf. ;
   FORMAT  EBPDSMH EBPDSMHf. ;
   FORMAT  ESUICSMH ESUICSMHf. ;
   FORMAT  EOPUDSMH EOPUDSMHf. ;
   FORMAT  PRMHDSMH PRMHDSMHf. ;
   FORMAT  EOMHSMH EOMHSMHf. ;
   FORMAT  EIMHSMH EIMHSMHf. ;
   FORMAT  OSEVSMH OSEVSMHf. ;
   FORMAT  EARTHRSMH EARTHRSMHf. ;
   FORMAT  AFALSMH AFALSMHf. ;
   FORMAT  BALNCSMH BALNCSMHf. ;
   FORMAT  EFALLSMH EFALLSMHf. ;
   FORMAT  FMEDSMH FMEDSMHf. ;
   FORMAT  FBBNSMH FBBNSMHf. ;
   FORMAT  FGUOOSMH FGUOOSMHf. ;
   FORMAT  EVBBNSMH EVBBNSMHf. ;
   FORMAT  EFHPSMH EFHPSMHf. ;
   FORMAT  EFHPOSMH EFHPOSMHf. ;
   FORMAT  EFSPSMH EFSPSMHf. ;
   FORMAT  EFSPOSMH EFSPOSMHf. ;
   FORMAT  EFWRSMH EFWRSMHf. ;
   FORMAT  EFWROSMH EFWROSMHf. ;
   FORMAT  EFOTBSMH EFOTBSMHf. ;
   FORMAT  EFOBOSMH EFOBOSMHf. ;
   FORMAT  ESHISMH ESHISMHf. ;
   FORMAT  MCOTSMH MCOTSMHf. ;
   FORMAT  OMEDSSMH OMEDSSMHf. ;
   FORMAT  PRPMSMH PRPMSMHf. ;
   FORMAT  PMRXSMH PMRXSMHf. ;
run;

%data (form=stblhha);
   FORMAT  SITE SITEf. ;
   FORMAT  EPRGSHH EPRGSHHf. ;
   FORMAT  PHBSSHH PHBSSHHf. ;
   FORMAT  PHYPSHH PHYPSHHf. ;
   FORMAT  PDPRSHH PDPRSHHf. ;
   FORMAT  PANXSHH PANXSHHf. ;
   FORMAT  POTHSHH POTHSHHf. ;
   FORMAT  DPRSSHH DPRSSHHf. ;
   FORMAT  ANX_SHH ANX_SHHf. ;
   FORMAT  SCHZSHH SCHZSHHf. ;
   FORMAT  PTSDSHH PTSDSHHf. ;
   FORMAT  BPLRSHH BPLRSHHf. ;
   FORMAT  SCDLSHH SCDLSHHf. ;
   FORMAT  MHOTSHH MHOTSHHf. ;
   FORMAT  MHDGSHH MHDGSHHf. ;
   FORMAT  MHRXSHH MHRXSHHf. ;
   FORMAT  OPMHSHH OPMHSHHf. ;
   FORMAT  IPMHSHH IPMHSHHf. ;
   FORMAT  PRXYSHH PRXYSHHf. ;
run;

%data (form=stblhhas1);
   FORMAT  MHDNDSHH MHDNDSHHf. ;
   FORMAT  MHDFQSHH MHDFQSHHf. ;
   FORMAT  MHDCUSHH MHDCUSHHf. ;
run;

%data (form=stblhhas2);
   FORMAT  PNDRXSHH PNDRXSHHf. ;
   FORMAT  PNDNDSHH PNDNDSHHf. ;
   FORMAT  PNDFQSHH PNDFQSHHf. ;
   FORMAT  PNDCUSHH PNDCUSHHf. ;
run;

%data (form=stblhhs1);
   FORMAT  METSSMH METSSMHf. ;
   FORMAT  SORGSMH SORGSMHf. ;
   FORMAT  CCT_SMH CCT_SMHf. ;
   FORMAT  CRADSMH CRADSMHf. ;
run;

%data (form=stblhhs2);
   FORMAT  ARVNDSMH ARVNDSMHf. ;
run;

%data (form=stblhhs3);
run;

%data (form=stblhhs4);
   FORMAT  PRPNDSMH PRPNDSMHf. ;
   FORMAT  PRPFQSMH PRPFQSMHf. ;
   FORMAT  PRPCUSMH PRPCUSMHf. ;
run;

%data (form=stblhhs5);
   FORMAT  PEPNDSMH PEPNDSMHf. ;
   FORMAT  PEPFQSMH PEPFQSMHf. ;
   FORMAT  PEPCUSMH PEPCUSMHf. ;
run;

%data (form=stblhhs6);
   FORMAT  HPBNDSMH HPBNDSMHf. ;
   FORMAT  HPBFQSMH HPBFQSMHf. ;
   FORMAT  HPBCUSMH HPBCUSMHf. ;
run;

%data (form=stblhhs7);
   FORMAT  HPCNDSMH HPCNDSMHf. ;
   FORMAT  HPCFQSMH HPCFQSMHf. ;
   FORMAT  HPCCUSMH HPCCUSMHf. ;
   FORMAT  MRSTSMH MRSTSMHf. ;
   FORMAT  MRTUSMH MRTUSMHf. ;
   FORMAT  MRHSESMH MRHSESMHf. ;
   FORMAT  MRBBSMH MRBBSMHf. ;
   FORMAT  MRBASMH MRBASMHf. ;
   FORMAT  MREXSMH MREXSMHf. ;
   FORMAT  MRAPSMH MRAPSMHf. ;
   FORMAT  MRHCSMH MRHCSMHf. ;
   FORMAT  MROTSMH MROTSMHf. ;
   FORMAT  SCTHSMH SCTHSMHf. ;
run;

%data (form=stblhhs9);
   FORMAT  HIHHSMH HIHHSMHf. ;
   FORMAT  HISDSMH HISDSMHf. ;
   FORMAT  HISHSMH HISHSMHf. ;
   FORMAT  HIKOSMH HIKOSMHf. ;
   FORMAT  HMHDSMH HMHDSMHf. ;
   FORMAT  HISFSMH HISFSMHf. ;
   FORMAT  HISZSMH HISZSMHf. ;
run;

%data (form=stblhhs10);
   FORMAT  OMDNDSMH OMDNDSMHf. ;
   FORMAT  OMDFQSMH OMDFQSMHf. ;
   FORMAT  OMDCUSMH OMDCUSMHf. ;
run;

%data (form=stblhosp);
   FORMAT  SITE SITEf. ;
   FORMAT  HOSPSHS HOSPSHSf. ;
   FORMAT  HCBRSHS HCBRSHSf. ;
   FORMAT  HINJSHS HINJSHSf. ;
   FORMAT  HELSSHS HELSSHSf. ;
   FORMAT  HNESSHS HNESSHSf. ;
   FORMAT  HPSYSHS HPSYSHSf. ;
   FORMAT  HILLSHS HILLSHSf. ;
   FORMAT  HIHPSHS HIHPSHSf. ;
   FORMAT  HISISHS HISISHSf. ;
   FORMAT  HILVSHS HILVSHSf. ;
   FORMAT  HIPNSHS HIPNSHSf. ;
   FORMAT  HIINSHS HIINSHSf. ;
   FORMAT  HILGSHS HILGSHSf. ;
   FORMAT  HIORSHS HIORSHSf. ;
   FORMAT  HODDPSHS HODDPSHSf. ;
   FORMAT  HOTHSHS HOTHSHSf. ;
run;

%data (form=stblhosps1);
   FORMAT  MRHCSHS MRHCSHSf. ;
   FORMAT  TYPHVSHS TYPHVSHSf. ;
run;

%data (form=stblhpv);
   FORMAT  SITE SITEf. ;
   FORMAT  EVHPVSHP EVHPVSHPf. ;
   FORMAT  VDSESSHP VDSESSHPf. ;
   FORMAT  STEFDSHP STEFDSHPf. ;
run;

%data (form=stblob);
   FORMAT  SITE SITEf. ;
   FORMAT  EBPREGSOB EBPREGSOBf. ;
   FORMAT  PREGSOB PREGSOBf. ;
   FORMAT  PNATSOB PNATSOBf. ;
   FORMAT  FPNVSOB FPNVSOBf. ;
   FORMAT  MCHLFSOB MCHLFSOBf. ;
   FORMAT  MCHLWSOB MCHLWSOBf. ;
   FORMAT  ACHLFSOB ACHLFSOBf. ;
   FORMAT  ACHLWSOB ACHLWSOBf. ;
   FORMAT  EHYSTSOB EHYSTSOBf. ;
   FORMAT  HRFIBSOB HRFIBSOBf. ;
   FORMAT  HRINFSOB HRINFSOBf. ;
   FORMAT  HRCNCSOB HRCNCSOBf. ;
   FORMAT  HRCOPSOB HRCOPSOBf. ;
   FORMAT  HRBLDSOB HRBLDSOBf. ;
   FORMAT  HRENDSOB HRENDSOBf. ;
   FORMAT  HRAPSSOB HRAPSSOBf. ;
   FORMAT  HRGAFSOB HRGAFSOBf. ;
   FORMAT  HROTHSOB HROTHSOBf. ;
   FORMAT  HRDKRSOB HRDKRSOBf. ;
   FORMAT  EMOVRSOB EMOVRSOBf. ;
   FORMAT  TLEVSOB TLEVSOBf. ;
   FORMAT  EPSTRVSOB EPSTRVSOBf. ;
   FORMAT  EPAP_SOB EPAP_SOBf. ;
   FORMAT  CPAPRSOB CPAPRSOBf. ;
   FORMAT  EAPAPSOB EAPAPSOBf. ;
   FORMAT  APAPRSOB APAPRSOBf. ;
   FORMAT  EHRANSOB EHRANSOBf. ;
   FORMAT  HRANRSOB HRANRSOBf. ;
   FORMAT  ECOLPSOB ECOLPSOBf. ;
   FORMAT  ECVABSOB ECVABSOBf. ;
   FORMAT  ABTXSOB ABTXSOBf. ;
   FORMAT  EOGYCSOB EOGYCSOBf. ;
   FORMAT  EGONOSOB EGONOSOBf. ;
   FORMAT  EVGONOSOB EVGONOSOBf. ;
   FORMAT  EOGONOSOB EOGONOSOBf. ;
   FORMAT  ERGONOSOB ERGONOSOBf. ;
   FORMAT  ESYPHSOB ESYPHSOBf. ;
   FORMAT  ESYDSGSOB ESYDSGSOBf. ;
   FORMAT  ESYDRASOB ESYDRASOBf. ;
   FORMAT  ESYDBTSOB ESYDBTSOBf. ;
   FORMAT  ECHLASOB ECHLASOBf. ;
   FORMAT  EVCHLASOB EVCHLASOBf. ;
   FORMAT  EOCHLASOB EOCHLASOBf. ;
   FORMAT  ERCHLASOB ERCHLASOBf. ;
   FORMAT  EGHERPSOB EGHERPSOBf. ;
   FORMAT  EAHERPSOB EAHERPSOBf. ;
   FORMAT  EGWARTSOB EGWARTSOBf. ;
   FORMAT  EAWARTSOB EAWARTSOBf. ;
   FORMAT  EPID_SOB EPID_SOBf. ;
   FORMAT  ETRICSOB ETRICSOBf. ;
   FORMAT  EBV__SOB EBV__SOBf. ;
   FORMAT  ECANDSOB ECANDSOBf. ;
   FORMAT  LSTPSOB LSTPSOBf. ;
   FORMAT  SKPPSOB SKPPSOBf. ;
   FORMAT  PLE_SOB PLE_SOBf. ;
   FORMAT  BPDSPSOB BPDSPSOBf. ;
   FORMAT  EVPOCSOB EVPOCSOBf. ;
   FORMAT  PNOPSOB PNOPSOBf. ;
   FORMAT  POCYUSOB POCYUSOBf. ;
   FORMAT  EBCPCHSOB EBCPCHSOBf. ;
   FORMAT  BCPYUSOB BCPYUSOBf. ;
   FORMAT  ENUVRSOB ENUVRSOBf. ;
   FORMAT  NUVYUSOB NUVYUSOBf. ;
   FORMAT  EIMPLSOB EIMPLSOBf. ;
   FORMAT  IMPYUSOB IMPYUSOBf. ;
   FORMAT  EDEPPSOB EDEPPSOBf. ;
   FORMAT  DEPYUSOB DEPYUSOBf. ;
   FORMAT  EIUDHSOB EIUDHSOBf. ;
   FORMAT  IUHYUSOB IUHYUSOBf. ;
   FORMAT  EIUDCSOB EIUDCSOBf. ;
   FORMAT  IUCYUSOB IUCYUSOBf. ;
   FORMAT  EERCPSOB EERCPSOBf. ;
   FORMAT  EDPHMSOB EDPHMSOBf. ;
   FORMAT  EMCNDSOB EMCNDSOBf. ;
   FORMAT  EFCNDSOB EFCNDSOBf. ;
   FORMAT  ENSEXSOB ENSEXSOBf. ;
   FORMAT  PROCSOB PROCSOBf. ;
   FORMAT  PRDPSOB PRDPSOBf. ;
   FORMAT  MENPSOB MENPSOBf. ;
   FORMAT  HFP2SOB HFP2SOBf. ;
   FORMAT  CSP2SOB CSP2SOBf. ;
   FORMAT  NSP2SOB NSP2SOBf. ;
   FORMAT  SJP2SOB SJP2SOBf. ;
   FORMAT  IGP2SOB IGP2SOBf. ;
   FORMAT  TNP2SOB TNP2SOBf. ;
   FORMAT  TFASSOB TFASSOBf. ;
   FORMAT  WKNTSOB WKNTSOBf. ;
   FORMAT  UFAASOB UFAASOBf. ;
   FORMAT  HRTXESOB HRTXESOBf. ;
   FORMAT  EESTROSOB EESTROSOBf. ;
   FORMAT  ESTYUSOB ESTYUSOBf. ;
   FORMAT  EPROGSSOB EPROGSSOBf. ;
   FORMAT  PROYUSOB PROYUSOBf. ;
   FORMAT  ECOMBOSOB ECOMBOSOBf. ;
   FORMAT  COMYUSOB COMYUSOBf. ;
   FORMAT  EOHORMSOB EOHORMSOBf. ;
   FORMAT  OHOYUSOB OHOYUSOBf. ;
   FORMAT  HBRSTSOB HBRSTSOBf. ;
   FORMAT  EMDNESOB EMDNESOBf. ;
   FORMAT  MRSNSOB MRSNSOBf. ;
   FORMAT  NDISSOB NDISSOBf. ;
   FORMAT  BPN_SOB BPN_SOBf. ;
   FORMAT  BPNPSOB BPNPSOBf. ;
   FORMAT  LUMPSOB LUMPSOBf. ;
run;

%data (form=stblobs1);
   FORMAT  POUTSOB POUTSOBf. ;
   FORMAT  BFEDSOB BFEDSOBf. ;
run;

%data (form=stblobs2);
  FORMAT  POCNDSOB POCNDSOBf. ;
   FORMAT  POCCUSOB POCCUSOBf. ;
run;

%data (form=stblobs3);
   FORMAT  DEPNDSOB DEPNDSOBf. ;
   FORMAT  DEPCUSOB DEPCUSOBf. ;
run;

%data (form=stblobs4);
   FORMAT  ESTNDSOB ESTNDSOBf. ;
   FORMAT  ESTFQSOB ESTFQSOBf. ;
   FORMAT  ESTCUSOB ESTCUSOBf. ;
run;

%data (form=stblobs5);
   FORMAT  PRONDSOB PRONDSOBf. ;
   FORMAT  PROFQSOB PROFQSOBf. ;
   FORMAT  PROCUSOB PROCUSOBf. ;
run;

%data (form=stblobs6);
   FORMAT  COMNDSOB COMNDSOBf. ;
   FORMAT  COMFQSOB COMFQSOBf. ;
   FORMAT  COMCUSOB COMCUSOBf. ;
run;

%data (form=stblobs7);
   FORMAT  OHONDSOB OHONDSOBf. ;
   FORMAT  OHOFQSOB OHOFQSOBf. ;
   FORMAT  OHOCUSOB OHOCUSOBf. ;
run;

%data (form=stbloral);
   FORMAT  SITE SITEf. ;
   FORMAT  CMTHSOH CMTHSOHf. ;
   FORMAT  LDENSOH LDENSOHf. ;
   FORMAT  DFRQSOH DFRQSOHf. ;
   FORMAT  WDENSOH WDENSOHf. ;
   FORMAT  PMTHSOH PMTHSOHf. ;
   FORMAT  PMIMSOH PMIMSOHf. ;
   FORMAT  PMOISOH PMOISOHf. ;
   FORMAT  PMFWSOH PMFWSOHf. ;
   FORMAT  PMATSOH PMATSOHf. ;
   FORMAT  PMTPSOH PMTPSOHf. ;
   FORMAT  PMAFSOH PMAFSOHf. ;
   FORMAT  PMWFSOH PMWFSOHf. ;
   FORMAT  HIVSSOH HIVSSOHf. ;
   FORMAT  HIVDSOH HIVDSOHf. ;
   FORMAT  HIVWSOH HIVWSOHf. ;
   FORMAT  PRGESOH PRGESOHf. ;
   FORMAT  ODNPSOH ODNPSOHf. ;
   FORMAT  PYSMSOH PYSMSOHf. ;
   FORMAT  PYGMSOH PYGMSOHf. ;
   FORMAT  PYGBSOH PYGBSOHf. ;
   FORMAT  PYTASOH PYTASOHf. ;
   FORMAT  PYTDSOH PYTDSOHf. ;
   FORMAT  PYLTSOH PYLTSOHf. ;
   FORMAT  PYSTSOH PYSTSOHf. ;
   FORMAT  PYPJSOH PYPJSOHf. ;
   FORMAT  PYBRSOH PYBRSOHf. ;
   FORMAT  PYBTSOH PYBTSOHf. ;
   FORMAT  PYBBSOH PYBBSOHf. ;
   FORMAT  PYAPSOH PYAPSOHf. ;
   FORMAT  DNKUSOH DNKUSOHf. ;
   FORMAT  DNRCSOH DNRCSOHf. ;
   FORMAT  DNNCSOH DNNCSOHf. ;
   FORMAT  DNBWSOH DNBWSOHf. ;
   FORMAT  DNCSSOH DNCSSOHf. ;
   FORMAT  DNDHSOH DNDHSOHf. ;
   FORMAT  DN12SOH DN12SOHf. ;
   FORMAT  DCTUSOH DCTUSOHf. ;
   FORMAT  DCAUSOH DCAUSOHf. ;
   FORMAT  DCDUSOH DCDUSOHf. ;
   FORMAT  DCOUSOH DCOUSOHf. ;
   FORMAT  DCBSSOH DCBSSOHf. ;
   FORMAT  DCBPSOH DCBPSOHf. ;
   FORMAT  DCFVSOH DCFVSOHf. ;
   FORMAT  DCHVSOH DCHVSOHf. ;
   FORMAT  DCPGSOH DCPGSOHf. ;
   FORMAT  RXOPSOH RXOPSOHf. ;
   FORMAT  OPDCSOH OPDCSOHf. ;
   FORMAT  OPPASOH OPPASOHf. ;
   FORMAT  OPAPSOH OPAPSOHf. ;
   FORMAT  OPLFSOH OPLFSOHf. ;
   FORMAT  OPUJSOH OPUJSOHf. ;
   FORMAT  OPSASOH OPSASOHf. ;
run;

%data (form=stblsd);
   FORMAT  SITE SITEf. ;
   FORMAT  EDUCSSD EDUCSSDf. ;
   FORMAT  MAR_SSD MAR_SSDf. ;
   FORMAT  RES_SSD RES_SSDf. ;
   FORMAT  SLN_SSD SLN_SSDf. ;
   FORMAT  LADDSSD LADDSSDf. ;
   FORMAT  LZIPSSD LZIPSSDf. ;
   FORMAT  SLNSSSD SLNSSSDf. ;
   FORMAT  WLSHSSD WLSHSSDf. ;
   FORMAT  EMPSTSSD EMPSTSSDf. ;
   FORMAT  WKWMSSD WKWMSSDf. ;
   FORMAT  WAGESSD WAGESSDf. ;
   FORMAT  SSI_SSD SSI_SSDf. ;
   FORMAT  SOCSSSD SOCSSSDf. ;
   FORMAT  DISBSSD DISBSSDf. ;
   FORMAT  HIUISSD HIUISSDf. ;
   FORMAT  HIVBSSD HIVBSSDf. ;
   FORMAT  HITASSD HITASSDf. ;
   FORMAT  HIGASSD HIGASSDf. ;
   FORMAT  OTSCSSD OTSCSSDf. ;
   FORMAT  INCMSSD INCMSSDf. ;
   FORMAT  HPFBSSD HPFBSSDf. ;
   FORMAT  JAILSSD JAILSSDf. ;
   FORMAT  PRJPYSSD PRJPYSSDf. ;
run;

%data (form=stblsds1);
 FORMAT  JSFEDSSD JSFEDSSDf. ;
   FORMAT  JLOCLSSD JLOCLSSDf. ;
   FORMAT  JOTHRSSD JOTHRSSDf. ;
   FORMAT  JMEDSSD JMEDSSDf. ;
run;

%data (form=stco);
   FORMAT  SITE SITEf. ;
   FORMAT  PENCCSSCO PENCCSSCOf. ;
run;

%data (form=stcons);
FORMAT  SITE SITEf. ;
   FORMAT  ECFOCSCT ECFOCSCTf. ;
   FORMAT  ECSTATSCT ECSTATSCTf. ;
   FORMAT  SMFOCSCT SMFOCSCTf. ;
   FORMAT  SMSTATSCT SMSTATSCTf. ;
   FORMAT  RMFOCSCT RMFOCSCTf. ;
   FORMAT  RMSTATSCT RMSTATSCTf. ;
   FORMAT  GLFOCSCT GLFOCSCTf. ;
   FORMAT  GLSTATSCT GLSTATSCTf. ;
   FORMAT  GCFOCSCT GCFOCSCTf. ;
   FORMAT  GCSTATSCT GCSTATSCTf. ;
   FORMAT  CFFOCSCT CFFOCSCTf. ;
   FORMAT  CFSTATSCT CFSTATSCTf. ;
run;

%data (form=stcont);
   FORMAT  SITE SITEf. ;
   FORMAT  WCONSCA WCONSCAf. ;
   FORMAT  UCONSCA UCONSCAf. ;
   FORMAT  SCONSCA SCONSCAf. ;
   FORMAT  NCPNOSCA NCPNOSCAf. ;
   FORMAT  NCPTYSCA NCPTYSCAf. ;
   FORMAT  NCPCHSCA NCPCHSCAf. ;
   FORMAT  NCHCPSCA NCHCPSCAf. ;
   FORMAT  NCAPPSCA NCAPPSCAf. ;
   FORMAT  NCNINSCA NCNINSCAf. ;
   FORMAT  NCIPYSCA NCIPYSCAf. ;
   FORMAT  NCHCNSCA NCHCNSCAf. ;
   FORMAT  NCSEFSCA NCSEFSCAf. ;
   FORMAT  FORMSCA FORMSCAf. ;
   FORMAT  IUDTSCA IUDTSCAf. ;
   FORMAT  TCPNOSCA TCPNOSCAf. ;
   FORMAT  TCPTYSCA TCPTYSCAf. ;
   FORMAT  TCPCHSCA TCPCHSCAf. ;
   FORMAT  TCHCPSCA TCHCPSCAf. ;
   FORMAT  TCAPPSCA TCAPPSCAf. ;
   FORMAT  TCNINSCA TCNINSCAf. ;
   FORMAT  TCIPYSCA TCIPYSCAf. ;
   FORMAT  TCHCNSCA TCHCNSCAf. ;
   FORMAT  TCSEFSCA TCSEFSCAf. ;
run;

%data (form=stcovid);
   FORMAT  SITE SITEf. ;
   FORMAT  PASKSCF PASKSCFf. ;
   FORMAT  EPOSSCF EPOSSCFf. ;
   FORMAT  LVTPSCF LVTPSCFf. ;
   FORMAT  CRCOVSCF CRCOVSCFf. ;
   FORMAT  HBMAWSCF HBMAWSCFf. ;
   FORMAT  HBMOSSCF HBMOSSCFf. ;
   FORMAT  HFATGSCF HFATGSCFf. ;
   FORMAT  HHDACSCF HHDACSCFf. ;
   FORMAT  HLSMLSCF HLSMLSCFf. ;
   FORMAT  HLTSTSCF HLTSTSCFf. ;
   FORMAT  HVISNSCF HVISNSCFf. ;
   FORMAT  HSPCHSCF HSPCHSCFf. ;
   FORMAT  HNTNGSCF HNTNGSCFf. ;
   FORMAT  HNTOSSCF HNTOSSCFf. ;
   FORMAT  HTIVMSCF HTIVMSCFf. ;
   FORMAT  HBLNCSCF HBLNCSCFf. ;
   FORMAT  HDZYSCF HDZYSCFf. ;
   FORMAT  HMEMSCF HMEMSCFf. ;
   FORMAT  HBFOGSCF HBFOGSCFf. ;
   FORMAT  HAPPTSCF HAPPTSCFf. ;
   FORMAT  HMOODSCF HMOODSCFf. ;
   FORMAT  HINSMSCF HINSMSCFf. ;
   FORMAT  HHAIRSCF HHAIRSCFf. ;
   FORMAT  HSEIZSCF HSEIZSCFf. ;
   FORMAT  HOTHRSCF HOTHRSCFf. ;
   FORMAT  RVACSCF RVACSCFf. ;
   FORMAT  NVACSCF NVACSCFf. ;
run;

%data (form=stcovids1);
   FORMAT  CSYMPSCF CSYMPSCFf. ;
   FORMAT  SPACTSCF SPACTSCFf. ;
   FORMAT  HOSPCSCF HOSPCSCFf. ;
   FORMAT  IHOXYSCF IHOXYSCFf. ;
   FORMAT  IHVNTSCF IHVNTSCFf. ;
   FORMAT  IHICUSCF IHICUSCFf. ;
   FORMAT  IHDIASCF IHDIASCFf. ;
   FORMAT  RECVRSCF RECVRSCFf. ;
run;

%data (form=stcovids2);
   FORMAT  KNMEVSCF KNMEVSCFf. ;
   FORMAT  WVACSCF WVACSCFf. ;
   FORMAT  VXDS1SCF VXDS1SCFf. ;
   FORMAT  VXDS2SCF VXDS2SCFf. ;
run;

%data (form=stdenr);
   FORMAT  SITE SITEf. ;
   FORMAT  DTSCSDE DTSCSDEf. ;
   FORMAT  DTSSSDE DTSSSDEf. ;
   FORMAT  RDNTSDE RDNTSDEf. ;
   FORMAT  SDFFSDE SDFFSDEf. ;
   FORMAT  SDHSSDE SDHSSDEf. ;
   FORMAT  SDDCSDE SDDCSDEf. ;
   FORMAT  SDOBSDE SDOBSDEf. ;
   FORMAT  SDPVSDE SDPVSDEf. ;
   FORMAT  SDASSDE SDASSDEf. ;
   FORMAT  SDSSSDE SDSSSDEf. ;
   FORMAT  SDNDSDE SDNDSDEf. ;
   FORMAT  SDOSSDE SDOSSDEf. ;
   FORMAT  FLUPSDE FLUPSDEf. ;
run;

%data (form=stel);
   FORMAT  SITE SITEf. ;
   FORMAT  LTNXSEL LTNXSELf. ;
   FORMAT  RCAASEL RCAASELf. ;
   FORMAT  RCWCSEL RCWCSELf. ;
   FORMAT  RCAISEL RCAISELf. ;
   FORMAT  RCASSEL RCASSELf. ;
   FORMAT  RCNHSEL RCNHSELf. ;
   FORMAT  RCOTSEL RCOTSELf. ;
   FORMAT  FOUTSEL FOUTSELf. ;
   FORMAT  TSTDSEL TSTDSELf. ;
   FORMAT  TPOSSEL TPOSSELf. ;
   FORMAT  MHIRSEL MHIRSELf. ;
   FORMAT  SPOM5SEL SPOM5SELf. ;
   FORMAT  SDMS5SEL SDMS5SELf. ;
   FORMAT  IDCOMSEL IDCOMSELf. ;
   FORMAT  STI5SEL STI5SELf. ;
   FORMAT  SXP5SEL SXP5SELf. ;
   FORMAT  PIDCOMSEL PIDCOMSELf. ;
   FORMAT  PSTISEL PSTISELf. ;
   FORMAT  PSPO5SEL PSPO5SELf. ;
   FORMAT  PSDMS5SEL PSDMS5SELf. ;
   FORMAT  PJL5SEL PJL5SELf. ;
   FORMAT  CFEMSEL CFEMSELf. ;
   FORMAT  AGE_SEL AGE_SELf. ;
   FORMAT  PMOVSEL PMOVSELf. ;
   FORMAT  CONSSEL CONSSELf. ;
   FORMAT  WBLDSEL WBLDSELf. ;
   FORMAT  WPDASEL WPDASELf. ;
   FORMAT  HSAASEL HSAASELf. ;
   FORMAT  HIVSSEL HIVSSELf. ;
   FORMAT  HMOTSEL HMOTSELf. ;
   FORMAT  RSX3MSEL RSX3MSELf. ;
   FORMAT  RIDUSEL RIDUSELf. ;
   FORMAT  RSTISEL RSTISELf. ;
   FORMAT  RSDMSSEL RSDMSSELf. ;
   FORMAT  RSPOMSEL RSPOMSELf. ;
   FORMAT  PRIDUSEL PRIDUSELf. ;
   FORMAT  PRSTISEL PRSTISELf. ;
   FORMAT  PRSX3SEL PRSX3SELf. ;
   FORMAT  PRSDMSEL PRSDMSELf. ;
   FORMAT  PRSPOSEL PRSPOSELf. ;
   FORMAT  PRJLSEL PRJLSELf. ;
   FORMAT  DISPSEL DISPSELf. ;
   FORMAT  DNRSSEL DNRSSELf. ;
   FORMAT  DNINSEL DNINSELf. ;
   FORMAT  DNCNSEL DNCNSELf. ;
   FORMAT  DBUSSEL DBUSSELf. ;
   FORMAT  DILLSEL DILLSELf. ;
   FORMAT  DCONSEL DCONSELf. ;
   FORMAT  DSHMSEL DSHMSELf. ;
   FORMAT  DOTHSEL DOTHSELf. ;
run;

%data (form=sthpvab);
   FORMAT  SITE SITEf. ;
   FORMAT  VIDPSSHV VIDPSSHVf. ;
   FORMAT  VVREGSHV VVREGSHVf. ;
   FORMAT  VVPMRSHV VVPMRSHVf. ;
   FORMAT  RRECDSHV RRECDSHVf. ;
   FORMAT  RNRRSSHV RNRRSSHVf. ;
   FORMAT  RRREGSHV RRREGSHVf. ;
   FORMAT  RRPMRSHV RRPMRSHVf. ;
   FORMAT  RDOCVSHV RDOCVSHVf. ;
   FORMAT  DOSE1SHV DOSE1SHVf. ;
   FORMAT  DS1DASHV DS1DASHVf. ;
   FORMAT  DOSE2SHV DOSE2SHVf. ;
   FORMAT  DS2DASHV DS2DASHVf. ;
   FORMAT  DOSE3SHV DOSE3SHVf. ;
   FORMAT  DS3DASHV DS3DASHVf. ;
run;

%data (form=stlab);
   FORMAT  SITE SITEf. ;
   FORMAT  LROBTSLB LROBTSLBf. ;
   FORMAT  HIVAVSLB HIVAVSLBf. ;
   FORMAT  SELISLB SELISLBf. ;
   FORMAT  ELISSLB ELISSLBf. ;
   FORMAT  SELRSLB SELRSLBf. ;
   FORMAT  HVAASLB HVAASLBf. ;
   FORMAT  CTM_SLB CTM_SLBf. ;
   FORMAT  WESTSLB WESTSLBf. ;
   FORMAT  IFA_SLB IFA_SLBf. ;
   FORMAT  MSPTSLB MSPTSLBf. ;
   FORMAT  HRQLSLB HRQLSLBf. ;
   FORMAT  HRQNSLB HRQNSLBf. ;
   FORMAT  CBCAVSLB CBCAVSLBf. ;
   FORMAT  DIFFSLB DIFFSLBf. ;
   FORMAT  LYMPSLB LYMPSLBf. ;
   FORMAT  POLYSLB POLYSLBf. ;
   FORMAT  MONOSLB MONOSLBf. ;
   FORMAT  EOSNSLB EOSNSLBf. ;
   FORMAT  BASOSLB BASOSLBf. ;
   FORMAT  HMCDNSLB HMCDNSLBf. ;
   FORMAT  HPOLYSLB HPOLYSLBf. ;
   FORMAT  HBANDSLB HBANDSLBf. ;
   FORMAT  HLYMPSLB HLYMPSLBf. ;
   FORMAT  HMONOSLB HMONOSLBf. ;
   FORMAT  HEOSNSLB HEOSNSLBf. ;
   FORMAT  HBASOSLB HBASOSLBf. ;
   FORMAT  HATLYSLB HATLYSLBf. ;
   FORMAT  HMETASLB HMETASLBf. ;
   FORMAT  HMYLOSLB HMYLOSLBf. ;
   FORMAT  HPROMSLB HPROMSLBf. ;
   FORMAT  HBLASSLB HBLASSLBf. ;
   FORMAT  FCYAVSLB FCYAVSLBf. ;
   FORMAT  CMNTSLB CMNTSLBf. ;
   FORMAT  C01_SLB C01_SLBf. ;
   FORMAT  C02_SLB C02_SLBf. ;
   FORMAT  C03_SLB C03_SLBf. ;
   FORMAT  LRTAVSLB LRTAVSLBf. ;
   FORMAT  CUAVSLB CUAVSLBf. ;
   FORMAT  CHLAVSLB CHLAVSLBf. ;
   FORMAT  CURRSLB CURRSLBf. ;
   FORMAT  CRSAVSLB CRSAVSLBf. ;
   FORMAT  CRSRSLB CRSRSLBf. ;
   FORMAT  COSAVSLB COSAVSLBf. ;
   FORMAT  CORRSLB CORRSLBf. ;
   FORMAT  GUAVSLB GUAVSLBf. ;
   FORMAT  GONAVSLB GONAVSLBf. ;
   FORMAT  GURRSLB GURRSLBf. ;
   FORMAT  GRSAVSLB GRSAVSLBf. ;
   FORMAT  GRSRSLB GRSRSLBf. ;
   FORMAT  GOSAVSLB GOSAVSLBf. ;
   FORMAT  GORRSLB GORRSLBf. ;
   FORMAT  TRCAVSLB TRCAVSLBf. ;
   FORMAT  TURRSLB TURRSLBf. ;
   FORMAT  SSCOLSLB SSCOLSLBf. ;
   FORMAT  STRPRSLB STRPRSLBf. ;
   FORMAT  STTRESLB STTRESLBf. ;
   FORMAT  STFTASLB STFTASLBf. ;
   FORMAT  STMHASLB STMHASLBf. ;
   FORMAT  RRPRSLB RRPRSLBf. ;
   FORMAT  TRRPRSLB TRRPRSLBf. ;
   FORMAT  RTRESLB RTRESLBf. ;
   FORMAT  RFTASLB RFTASLBf. ;
   FORMAT  RMHASLB RMHASLBf. ;
   FORMAT  CTRPRSLB CTRPRSLBf. ;
   FORMAT  CTTRESLB CTTRESLBf. ;
   FORMAT  CTFTASLB CTFTASLBf. ;
   FORMAT  CTMHASLB CTMHASLBf. ;
   FORMAT  CRRPRSLB CRRPRSLBf. ;
   FORMAT  CTRRPRSLB CTRRPRSLBf. ;
   FORMAT  CRTRESLB CRTRESLBf. ;
   FORMAT  CRFTASLB CRFTASLBf. ;
   FORMAT  CRMHASLB CRMHASLBf. ;
run;

%data (form=stlab);
   FORMAT  SITE SITEf. ;
   FORMAT  BPARMSPE BPARMSPEf. ;
   FORMAT  DIMGSPE DIMGSPEf. ;
  /* FORMAT  RNIMGSPE RNIMGSPEf. ; */
   FORMAT  IMGUASPE IMGUASPEf. ;
   FORMAT  IMGLASPE IMGLASPEf. ;
   FORMAT  IMGSVSPE IMGSVSPEf. ;
run;

%data (form=stprasc);
   FORMAT  SITE SITEf. ;
   FORMAT  DATASPA DATASPAf. ;
   FORMAT  MULTISPA MULTISPAf. ;
   FORMAT  OUTLSSPA OUTLSSPAf. ;
   FORMAT  ARMDPSPA ARMDPSPAf. ;
   FORMAT  AOAPDSPA AOAPDSPAf. ;
   FORMAT  CHARVSPA CHARVSPAf. ;
   FORMAT  TCPASPA TCPASPAf. ;
   FORMAT  HRPASPA HRPASPAf. ;
   FORMAT  HRPBLSPA HRPBLSPAf. ;
   FORMAT  HR1ASPA HR1ASPAf. ;
   FORMAT  HR1BLSPA HR1BLSPAf. ;
   FORMAT  HR2ASPA HR2ASPAf. ;
   FORMAT  HR2BLSPA HR2BLSPAf. ;
   FORMAT  HR3ASPA HR3ASPAf. ;
   FORMAT  HR3BLSPA HR3BLSPAf. ;
   FORMAT  HRDASPA HRDASPAf. ;
   FORMAT  HRDBLSPA HRDBLSPAf. ;
   FORMAT  TCDASPA TCDASPAf. ;
   FORMAT  HIVSSPA HIVSSPAf. ;
   FORMAT  HTSTPSPA HTSTPSPAf. ;
   FORMAT  GONOSPA GONOSPAf. ;
   FORMAT  CHLASPA CHLASPAf. ;
   FORMAT  TRCHSPA TRCHSPAf. ;
   FORMAT  SYPHSPA SYPHSPAf. ;
   FORMAT  SWTTSPA SWTTSPAf. ;
   FORMAT  TOXESPA TOXESPAf. ;
   FORMAT  CCHOSPA CCHOSPAf. ;
   FORMAT  PHYDSPA PHYDSPAf. ;
   FORMAT  OHYDSPA OHYDSPAf. ;
   FORMAT  IUGRSPA IUGRSPAf. ;
   FORMAT  GDIASPA GDIASPAf. ;
   FORMAT  OINFSPA OINFSPAf. ;
   FORMAT  OSINSPA OSINSPAf. ;
   FORMAT  HELPSPA HELPSPAf. ;
   FORMAT  PLABSPA PLABSPAf. ;
   FORMAT  PLPRSPA PLPRSPAf. ;
   FORMAT  ELBPSPA ELBPSPAf. ;
   FORMAT  PTLBSPA PTLBSPAf. ;
   FORMAT  APAPSPA APAPSPAf. ;
   FORMAT  STRPSPA STRPSPAf. ;
   FORMAT  GAGESPA GAGESPAf. ;
   FORMAT  GDLMPSPA GDLMPSPAf. ;
   FORMAT  GDIUSSPA GDIUSSPAf. ;
   FORMAT  GDMPESPA GDMPESPAf. ;
   FORMAT  GDOTHSPA GDOTHSPAf. ;
   FORMAT  MDLVSPA MDLVSPAf. ;
   FORMAT  IVZIDSPA IVZIDSPAf. ;
   FORMAT  PPVISSPA PPVISSPAf. ;
   FORMAT  HRAASPA HRAASPAf. ;
   FORMAT  HRABLSPA HRABLSPAf. ;
run;

%data (form=stprascs1);
   FORMAT  OUTCSPA OUTCSPAf. ;
run;

%data (form=stprascs2);
   FORMAT  FARVNDSPA FARVNDSPAf. ;
run;

%data (form=stprascs3);
   FORMAT  DARVNDSPA DARVNDSPAf. ;
run;

%data (form=stprhh);
   FORMAT  SITE SITEf. ;
   FORMAT  CPRGSPH CPRGSPHf. ;
   FORMAT  OCPGSPH OCPGSPHf. ;
   FORMAT  APNCSPH APNCSPHf. ;
   FORMAT  PCONSPH PCONSPHf. ;
   FORMAT  NBCRSPH NBCRSPHf. ;
   FORMAT  MCONSPH MCONSPHf. ;
   FORMAT  WBBYSPH WBBYSPHf. ;
   FORMAT  TIMPSPH TIMPSPHf. ;
   FORMAT  POHLSPH POHLSPHf. ;
   FORMAT  PMHLSPH PMHLSPHf. ;
   FORMAT  D7ALSPH D7ALSPHf. ;
   FORMAT  D7EJSPH D7EJSPHf. ;
   FORMAT  D7BMSPH D7BMSPHf. ;
   FORMAT  D7AWSPH D7AWSPHf. ;
   FORMAT  D7SPSPH D7SPSPHf. ;
   FORMAT  D7OTSPH D7OTSPHf. ;
   FORMAT  D7DSSPH D7DSSPHf. ;
   FORMAT  D7SMSPH D7SMSPHf. ;
   FORMAT  D7UCSPH D7UCSPHf. ;
   FORMAT  D7CRSPH D7CRSPHf. ;
   FORMAT  D7HMSPH D7HMSPHf. ;
run;

%data (form=stprr);
   FORMAT  SITE SITEf. ;
   FORMAT  PRPTSPR PRPTSPRf. ;
run;

%data (form=strab);
   FORMAT  SITE SITEf. ;
   FORMAT  HIVTSRA HIVTSRAf. ;
   FORMAT  EARTSRA EARTSRAf. ;
   FORMAT  ART_SRA ART_SRAf. ;
   FORMAT  MRIDSRA MRIDSRAf. ;
   FORMAT  HIDPSRA HIDPSRAf. ;
   FORMAT  HIPPRSRA HIPPRSRAf. ;
   FORMAT  HRBLSRA HRBLSRAf. ;
   FORMAT  ADDRSRA ADDRSRAf. ;
run;

%data (form=strabs1);
   FORMAT  HPRGSRA HPRGSRAf. ;
   FORMAT  HPPRESRA HPPRESRAf. ;
run;

%data (form=strabs2);
run;

%data (form=strsp);
   FORMAT  SITE SITEf. ;
   FORMAT  SERRSRS SERRSRSf. ;
   FORMAT  CPTRSRS CPTRSRSf. ;
   FORMAT  CELSSRS CELSSRSf. ;
   FORMAT  EDTRSRS EDTRSRSf. ;
   FORMAT  URNRSRS URNRSRSf. ;
   FORMAT  HPVRSRS HPVRSRSf. ;
   FORMAT  VGSRSRS VGSRSRSf. ;
   FORMAT  ORLRSRS ORLRSRSf. ;
   FORMAT  RECRSRS RECRSRSf. ;
   FORMAT  SLVRSRS SLVRSRSf. ;
run;

%data (form=stsc);
   FORMAT  SITE SITEf. ;
   FORMAT  LLTDSSP LLTDSSPf. ;
   FORMAT  FASTSSP FASTSSPf. ;
   FORMAT  PRGOBSSP PRGOBSSPf. ;
   FORMAT  PRGSRSSP PRGSRSSPf. ;
   FORMAT  PRSLTSSP PRSLTSSPf. ;
   FORMAT  HAAOBSSP HAAOBSSPf. ;
   FORMAT  HAASRSSP HAASRSSPf. ;
   FORMAT  CBCOBSSP CBCOBSSPf. ;
   FORMAT  CBCSRSSP CBCSRSSPf. ;
   FORMAT  CDPOBSSP CDPOBSSPf. ;
   FORMAT  CDPSRSSP CDPSRSSPf. ;
   FORMAT  HRNOBSSP HRNOBSSPf. ;
   FORMAT  HRNSRSSP HRNSRSSPf. ;
   FORMAT  CMPOBSSP CMPOBSSPf. ;
   FORMAT  CMPSRSSP CMPSRSSPf. ;
   FORMAT  LIPOBSSP LIPOBSSPf. ;
   FORMAT  LIPSRSSP LIPSRSSPf. ;
   FORMAT  A1COBSSP A1COBSSPf. ;
   FORMAT  A1CSRSSP A1CSRSSPf. ;
   FORMAT  BLVOMSSP BLVOMSSPf. ;
   FORMAT  SYPOBSSP SYPOBSSPf. ;
   FORMAT  SYPSRSSP SYPSRSSPf. ;
   FORMAT  CGROBSSP CGROBSSPf. ;
   FORMAT  CGRSRSSP CGRSRSSPf. ;
   FORMAT  CGOOBSSP CGOOBSSPf. ;
   FORMAT  CGOSRSSP CGOSRSSPf. ;
   FORMAT  CGTOBSSP CGTOBSSPf. ;
   FORMAT  CGTSRSSP CGTSRSSPf. ;
   FORMAT  CREPCSSP CREPCSSPf. ;
   FORMAT  CPPOBSSP CPPOBSSPf. ;
   FORMAT  CPPSRSSP CPPSRSSPf. ;
   FORMAT  CPVOBSSP CPVOBSSPf. ;
   FORMAT  CPVSRSSP CPVSRSSPf. ;
   FORMAT  EDTOBSSP EDTOBSSPf. ;
   FORMAT  EDTSRSSP EDTSRSSPf. ;
   FORMAT  SEROBSSP SEROBSSPf. ;
   FORMAT  SERSRSSP SERSRSSPf. ;
   FORMAT  URNOBSSP URNOBSSPf. ;
   FORMAT  URNSRSSP URNSRSSPf. ;
   FORMAT  VSCOBSSP VSCOBSSPf. ;
   FORMAT  VSCSRSSP VSCSRSSPf. ;
   FORMAT  VSROBSSP VSROBSSPf. ;
   FORMAT  VSRSRSSP VSRSRSSPf. ;
   FORMAT  OSROBSSP OSROBSSPf. ;
   FORMAT  OSRSRSSP OSRSRSSPf. ;
   FORMAT  RSROBSSP RSROBSSPf. ;
   FORMAT  RSRSRSSP RSRSRSSPf. ;
   FORMAT  HAIOBSSP HAIOBSSPf. ;
   FORMAT  HAISRSSP HAISRSSPf. ;
   FORMAT  HAISTSSP HAISTSSPf. ;
   FORMAT  OSVOBSSP OSVOBSSPf. ;
   FORMAT  OSVSRSSP OSVSRSSPf. ;
   FORMAT  OSSOBSSP OSSOBSSPf. ;
   FORMAT  OSSSRSSP OSSSRSSPf. ;
   FORMAT  FD90SSP FD90SSPf. ;
   FORMAT  BFR90SSP BFR90SSPf. ;
run;

****************
***MERGE CODE***
****************
;

*SORTING FOR MERGE;
%macro sort(form=);
proc sort data=STAR.&form;
by STARID;
run;
%mend;

%sort (form=stel);		%sort (form=stasc);		%sort (form=staer);		%sort (form=stascs1);
%sort (form=stascs2);	%sort (form=stascs3);	%sort (form=stascs4);	%sort (form=stblbeh);
%sort (form=stblcovid);	%sort (form=stblhcu);	%sort (form=stblhh);	%sort (form=stblhha);
%sort (form=stblhhas1);	%sort (form=stblhhas2);	%sort (form=stblhhs1);	%sort (form=stblhhs2);
%sort (form=stblhhs3);	%sort (form=stblhhs4);	%sort (form=stblhhs5);	%sort (form=stblhhs6);
%sort (form=stblhhs7);	%sort (form=stblhhs9);	%sort (form=stblhhs10);	%sort (form=stblhosp);
%sort (form=stblhosps1);%sort (form=stblhpv);	%sort (form=stblob);	%sort (form=stblobs1);
%sort (form=stblobs2);	%sort (form=stblobs3);	%sort (form=stblobs4);	%sort (form=stblobs5);
%sort (form=stblobs6);	%sort (form=stblobs7);	%sort (form=stbloral);	%sort (form=stblsd);
%sort (form=stblsds1);	%sort (form=stco);		%sort (form=stcons);	%sort (form=stcont);
%sort (form=stcovid);	%sort (form=stcovids1);	%sort (form=stcovids2);	%sort (form=stdenr);
%sort (form=sthpvab);	%sort (form=stlab);		%sort (form=stpe);		%sort (form=stprasc);	
%sort (form=stprascs1);	%sort (form=stprascs2);	%sort (form=stprascs3);	%sort (form=stprhh);	
%sort (form=stprr);		%sort (form=strab);		%sort (form=strabs1);	%sort (form=strabs2);	
%sort (form=strsp);		%sort (form=stsc);

*EXCLUDING FORMS WITH MULTIPLE VISITS;
%macro visit(form=);
title "&form. - Visits above 10 or 11?";
proc freq data=STAR.&form;
table VISIT;
where VISIT>11;
run;
title;
%mend;

%visit (form=stel);			%visit (form=staer);		%visit (form=stascs2);		%visit (form=stascs3);		
%visit (form=stascs4);		%visit (form=stblbeh);		%visit (form=stblhcu);		%visit (form=stblhh);		
%visit (form=stblhha);		%visit (form=stblhhas1);	%visit (form=stblhhas2);	%visit (form=stblhhs1);		
%visit (form=stblhhs2);		%visit (form=stblhhs3);		%visit (form=stblhhs4);		%visit (form=stblhhs5);		
%visit (form=stblhhs6);		%visit (form=stblhhs7);		%visit (form=stblhhs9);		%visit (form=stblhhs10);	
%visit (form=stblhosp);		%visit (form=stblhosps1);	%visit (form=stblhpv);		%visit (form=stblob);		
%visit (form=stblobs1);		%visit (form=stblobs2);		%visit (form=stblobs3);		%visit (form=stblobs4);		
%visit (form=stblobs5);		%visit (form=stblobs6);		%visit (form=stblobs7);		%visit (form=stbloral);		
%visit (form=stblsd);		%visit (form=stblsds1);		%visit (form=stprascs3);

*MULTIPLE VISITS ABOVE V10 or V11;
%visit (form=stasc);		%visit (form=stascs1);		%visit (form=stblcovid);	%visit (form=stco);			
%visit (form=stcons);		%visit (form=stcont);		%visit (form=stcovid);		%visit (form=stcovids1);	
%visit (form=stcovids2);	%visit (form=stdenr);		%visit (form=sthpvab);		%visit (form=stlab);		
%visit (form=stpe);			%visit (form=stprasc);		%visit (form=stprascs1);	%visit (form=stprascs2);
%visit (form=stprhh);		%visit (form=stprr);		%visit (form=strab);		%visit (form=strabs1);
%visit (form=strabs2);		%visit (form=strsp);		%visit (form=stsc);

*RENAME ALL VARIABLES WITH _FORM PREFIX EXCEPT STARID, VISIT, AND SITE;
%macro rename(form=);
proc sql noprint;
select cats(name,"=",name,"_&form") 
into :rename_list_suffix separated by " "
from dictionary.columns
where libname="STAR" 
and memname="&form";
quit; 

/*%PUT &=rename_list_suffix.;*/

data STAR.&form;
	set STAR.&form (rename=(&rename_list_suffix.));
rename STARID_&form=STARID VISIT_&form=VISIT SITE_&form=SITE;
run;
%mend;

%RENAME (FORM=STEL);		%RENAME (FORM=STAER);		%RENAME (FORM=STASCS2);		%RENAME (FORM=STASCS3);		
%RENAME (FORM=STASCS4);		%RENAME (FORM=STBLBEH);		%RENAME (FORM=STBLHCU);		%RENAME (FORM=STBLHH);		
%RENAME (FORM=STBLHHA);		%RENAME (FORM=STBLHHAS1);	%RENAME (FORM=STBLHHAS2);	%RENAME (FORM=STBLHHS1);		
%RENAME (FORM=STBLHHS2);	%RENAME (FORM=STBLHHS3);	%RENAME (FORM=STBLHHS4);	%RENAME (FORM=STBLHHS5);		
%RENAME (FORM=STBLHHS6);	%RENAME (FORM=STBLHHS7);	%RENAME (FORM=STBLHHS9);	%RENAME (FORM=STBLHHS10);	
%RENAME (FORM=STBLHOSP);	%RENAME (FORM=STBLHOSPS1);	%RENAME (FORM=STBLHPV);		%RENAME (FORM=STBLOB);		
%RENAME (FORM=STBLOBS1);	%RENAME (FORM=STBLOBS2);	%RENAME (FORM=STBLOBS3);	%RENAME (FORM=STBLOBS4);		
%RENAME (FORM=STBLOBS5);	%RENAME (FORM=STBLOBS6);	%RENAME (FORM=STBLOBS7);	%RENAME (FORM=STBLORAL);		
%RENAME (FORM=STBLSD);		%RENAME (FORM=STBLSDS1);	%RENAME (FORM=STPRASCS3);

*MULTIPLE VISITS ABOVE V10 OR V11;
%RENAME (FORM=STASC);		%RENAME (FORM=STASCS1);		%RENAME (FORM=STBLCOVID);	%RENAME (FORM=STCO);			
%RENAME (FORM=STCONS);		%RENAME (FORM=STCONT);		%RENAME (FORM=STCOVID);		%RENAME (FORM=STCOVIDS1);	
%RENAME (FORM=STCOVIDS2);	%RENAME (FORM=STDENR);		%RENAME (FORM=STHPVAB);		%RENAME (FORM=STLAB);		
%RENAME (FORM=STPE);		%RENAME (FORM=STPRASC);		%RENAME (FORM=STPRASCS1);	%RENAME (FORM=STPRASCS2);
%RENAME (FORM=STPRHH);		%RENAME (FORM=STPRR);		%RENAME (FORM=STRAB);		%RENAME (FORM=STRABS1);
%RENAME (FORM=STRABS2);		%RENAME (FORM=STRSP);		%RENAME (FORM=STSC);

******************************
***DELELE IF NOT V10 or V11***
******************************
;
%macro baseline(form=);
data STAR.&form._bl;
set STAR.&form;
if visit>11 then DELETE;
run;
%mend;

*MULTIPLE VISITS ABOVE V10 OR V11;
%baseline (form=stasc);		%baseline (form=stascs1);	%baseline (form=stblcovid);	%baseline (form=stco);			
%baseline (form=stcons);	%baseline (form=stcont);	%baseline (form=stcovid);	%baseline (form=stcovids1);	
%baseline (form=stcovids2);	%baseline (form=stdenr);	%baseline (form=sthpvab);	%baseline (form=stlab);		
%baseline (form=stpe);		%baseline (form=stprasc);	%baseline (form=stprascs1);	%baseline (form=stprascs2);
%baseline (form=stprhh);	%baseline (form=stprr);		%baseline (form=strab);		%baseline (form=strabs1);
%baseline (form=strabs2);	%baseline (form=strsp);		%baseline (form=stsc);

%macro dup2 (form=);
proc freq data=STAR.&form noprint;
table STARID / out=&form._freq;
run;

data &form._freq;
set &form._freq;
if COUNT<2 then DELETE;
run;

proc sql noprint;
select STARID 
into :STARID separated by " " 
from &form._freq;
quit; 

%PUT &form - IDs with duplication;
%PUT &=STARID;

%mend;

*FORMS WITHOUT DUPLICATE IDs;
%dup2 (form=staer);			%dup2 (form=stascs2);		%dup2 (form=stblbeh);		%dup2 (form=stblhcu);		
%dup2 (form=stblhh);		%dup2 (form=stblhha);		%dup2 (form=stblhhs3);		%dup2 (form=stblhhs4);		
%dup2 (form=stblhhs5);		%dup2 (form=stblhhs6);		%dup2 (form=stblhhs7);		%dup2 (form=stblob);		
%dup2 (form=stblobs4);		%dup2 (form=stblobs5);		%dup2 (form=stblobs6);		%dup2 (form=stblobs7);				
%dup2 (form=stasc_bl);		%dup2 (form=stascs1_bl);	%dup2 (form=stblcovid_bl);	%dup2 (form=stco_bl);			
%dup2 (form=stcons_bl);		%dup2 (form=stcont_bl);		%dup2 (form=stcovid_bl);	%dup2 (form=stdenr_bl);			
%dup2 (form=stprasc_bl);	%dup2 (form=stprascs1_bl);	%dup2 (form=stprhh_bl);		%dup2 (form=stprr_bl);				
%dup2 (form=strsp_bl);				

%dup2 (form=stpe_bl);		%dup2 (form=stblsd);		%dup2 (form=stbloral);		%dup2 (form=stblhpv);
%dup2 (form=stblhosp);		%dup2 (form=stel);

*FORMS WITH DUPLICATE IDS THAT SHOULD NOT HAVE DUPLICATE IDS;		
%dup2 (form=sthpvab_bl);*+;	%dup2 (form=stlab_bl);*1;	%dup2 (form=strab_bl);*1;	%dup2 (form=stsc_bl);*1;

*FORMS WITH DUPLICATE IDs FOUND;
%dup2 (form=stascs3);*1;		%dup2 (form=stascs4);*1;		%dup2 (form=stblhhas1);*25;		%dup2 (form=stblhhas2);*35;		
%dup2 (form=stblhhs1);*1;		%dup2 (form=stblhhs2);*75;		%dup2 (form=stblhhs9);*19;		%dup2 (form=stblhhs10);*219;			
%dup2 (form=stblhosps1);*70;	%dup2 (form=stblobs1);*360;		%dup2 (form=stblobs2);*2;		%dup2 (form=stblobs3);*1;	
%dup2 (form=stblsds1);*11;		%dup2 (form=stprascs3);*1;		%dup2 (form=stcovids1_bl);*9;	%dup2 (form=stcovids2_bl);*144;		
%dup2 (form=stprascs2_bl);*2;	%dup2 (form=strabs1_bl);*117;	%dup2 (form=strabs2_bl);*181;

*PREVIOUS FIXES;
/*
%dup2 (form=stel);*1;
data STAR.stel;
set STAR.stel;
if STARID=7611856 and VISIT=10 then DELETE;
run;

%dup2 (form=stblhosp);*1;
data STAR.stblhosp;
set STAR.stblhosp;
if STARID=7310921 and VISIT=11 then DELETE;
run;

%dup2 (form=stblhpv);*1;
data STAR.stblhpv;
set STAR.stblhpv;
if STARID=7310921 and VISIT=11 then DELETE;
run;

%dup2 (form=stbloral);*1;
data STAR.stbloral;
set STAR.stbloral;
if STARID=7310921 and VISIT=11 then DELETE;
run;

%dup2 (form=stblsd);*1;	
data STAR.stblsd;
set STAR.stblsd;
if STARID=7311002 and VISIT=10 then DELETE;
run;

%dup2 (form=stpe_bl);*1;
data STAR.stpe_bl;
set STAR.stpe_bl;
if STARID=7315051 and VISIT=10 then DELETE;
run;

%dup2 (form=sthpvab_bl);*+;
data STAR.sthpvab_bl;
set STAR.sthpvab_bl;
if STARID=7310818 and VISIT=10 then DELETE;
if STARID=7310863 and VISIT=10 then DELETE;
if STARID=7311002 and VISIT=10 then DELETE;
if STARID=7315051 and VISIT=10 then DELETE;
if STARID=7315313 and VISIT=10 then DELETE;
if STARID=7410331 and VISIT=10 then DELETE;
run;

*/
data STAR.sthpvab_bl;
set STAR.sthpvab_bl;
if STARID=7410331 and _N_=143 then DELETE;
run;
%dup2 (form=sthpvab_bl);


data STAR.stlab_bl;
set STAR.stlab_bl;
if STARID=7310067 and VISIT=11 then DELETE;
run;
%dup2 (form=stlab_bl);

data STAR.strab_bl;
set STAR.strab_bl;
if STARID=7410331 and _N_=85 then DELETE;
run;
%dup2 (form=strab_bl);	

data STAR.stsc_bl;
set STAR.stsc_bl;
if STARID=7410331 and _N_=216 then DELETE;
run;
%dup2 (form=stsc_bl);

/*
*FORMS WITH DUPLICATE IDs FOUND;
%dup2 (form=stascs3);*1;		%dup2 (form=stascs4);*1;		%dup2 (form=stblhhas1);*25;		%dup2 (form=stblhhas2);*35;		
%dup2 (form=stblhhs1);*1;		%dup2 (form=stblhhs2);*75;		%dup2 (form=stblhhs9);*19;		%dup2 (form=stblhhs10);*219;			
%dup2 (form=stblhosps1);*70;	%dup2 (form=stblobs1);*360;		%dup2 (form=stblobs2);*2;		%dup2 (form=stblobs3);*1;	
%dup2 (form=stblsds1);*11;		%dup2 (form=stprascs3);*1;		%dup2 (form=stcovids1_bl);*9;	%dup2 (form=stcovids2_bl);*144;		
%dup2 (form=stprascs2_bl);*2;	%dup2 (form=strabs1_bl);*117;	%dup2 (form=strabs2_bl);*181;
*/

***********
***MERGE***
***********
;
data STAR.STAR_bl;
merge STAR.stel (in=a)

/*FORMS WITHOUT DUPLICATE IDs;*/
STAR.staer		STAR.stascs2		STAR.stblbeh		STAR.stblhcu		
STAR.stblhh		STAR.stblhha		STAR.stblhhs3		STAR.stblhhs4		
STAR.stblhhs5	STAR.stblhhs6		STAR.stblhhs7		STAR.stblob		
STAR.stblobs4	STAR.stblobs5		STAR.stblobs6		STAR.stblobs7				
STAR.stasc_bl	STAR.stascs1_bl		STAR.stblcovid_bl	STAR.stco_bl			
STAR.stcons_bl	STAR.stcont_bl		STAR.stcovid_bl		STAR.stdenr_bl			
STAR.stprasc_bl	STAR.stprascs1_bl	STAR.stprhh_bl		STAR.stprr_bl				
STAR.strsp_bl	

STAR.stpe_bl	STAR.stblsd			STAR.stbloral		STAR.stblhpv
STAR.stblhosp	

/*FORMS WITH DUPLICATE IDS THAT SHOULD NOT HAVE DUPLICATE IDS;*/
STAR.sthpvab_bl	STAR.stlab_bl		STAR.strab_bl		STAR.stsc_bl;
by STARID;
if a=1;
run;

proc sort data=STAR.STAR_bl;
by STARID;
run;

data STAR.STAR_bl;
set STAR.STAR_bl;

*AGE CALCULATION;
COMP_N=input(DCMPSEL_STEL,mmddyy8.);
DOB=mdy(DOBMSEL_STEL,DOBDSEL_STEL,DOBYSEL_STEL);
format COMP_N DOB mmddyy8.;
AGE=INT((COMP_N-DOB)/365.25);
IF AGE <=0 then AGE=.;
EL_YEAR=year(COMP_N);

*RACE RECODE;
if RCAASEL_STEL=. and RCWCSEL_STEL=. and RCAISEL_STEL=. and
RCASSEL_STEL=. and RCNHSEL_STEL=. and RCOTSEL_STEL=. then RACE=.;
else if RCAASEL_STEL=1 then RACE=1;
else if RCWCSEL_STEL=1 then RACE=2;
else if RCAISEL_STEL=1 then RACE=3;
else if RCASSEL_STEL=1 then RACE=4;
else if RCNHSEL_STEL=1 then RACE=5;
else if RCOTSEL_STEL=1 then RACE=6;
MULTI= RCAASEL_STEL + RCWCSEL_STEL + RCAISEL_STEL
+ RCASSEL_STEL + RCNHSEL_STEL + RCOTSEL_STEL;
if MULTI>1 then RACE=7;

length RACE_CAT $ 30;
if RACE=1 then RACE_CAT="Black/African American";
if RACE=2 then RACE_CAT="White/Caucasian";
if RACE=3 then RACE_CAT="American Indian/Alaskan Native";
if RACE=4 then RACE_CAT="Asian";
if RACE=5 then RACE_CAT="Native Hawaiian/Other Pacific Islander";
if RACE=6 then RACE_CAT="Other";
if RACE=7 then RACE_CAT="Multiracial";

if WGHTSPE_STPE>0 and HGHTSPE_STPE>0 then do;
BMI=WGHTSPE_STPE/((HGHTSPE_STPE/100)**2);
end;
else BMI=.;

run;

***END HERE***;

proc contents data=STAR.STAR_bl varnum;
run;

*************************************************************************;
*************************************************************************;
*************************************************************************;

*****************
***COVID & HIV***
*****************
;


data STAR.STAR_bl_clean;
set STAR.STAR_bl;

*EVER TESTED POSITIVE FOR COVID;
if EPOSSCF_STCOVID=. then EVER_POS_COVID=TPOSSCV_STBLCOVID;
else if TPOSSCV_STBLCOVID=. then EVER_POS_COVID=EPOSSCF_STCOVID;

*COMPLETELY RECOVERED FROM MOST RECENT COVID;
if CRCOVSCF_STCOVID=. then COVID_RECOVERY=RECVRSCV_STBLCOVID;
else if RECVRSCV_STBLCOVID=. then COVID_RECOVERY=CRCOVSCF_STCOVID;

%macro covmerge (stblcovid=, stcovid=,new_var=);
if &stcovid=. then &new_var=&stblcovid;
else if &stblcovid=. then &new_var=&stcovid;
%mend;

/*Body or muscle aches, body pain or muscle weakness.........................................................*/  
%covmerge (stblcovid=HBMAWSCV_STBLCOVID, stcovid=HBMAWSCF_STCOVID,new_var=MUSCLE_ACHES); 
/*Was this on just one side of the body?.....................................................................*/  
%covmerge (stblcovid=HBMOSSCV_STBLCOVID, stcovid=HBMOSSCF_STCOVID,new_var=SIDE_MUSCLE_ACHES);
/*Fatigue or lack of energy..................................................................................*/  
%covmerge (stblcovid=HFATGSCV_STBLCOVID, stcovid=HFATGSCF_STCOVID,new_var=FATIGUE);
/*Headache...................................................................................................*/  
%covmerge (stblcovid=HHDACSCV_STBLCOVID, stcovid=HHDACSCF_STCOVID,new_var=HEADACHE);
/*Loss of smell..............................................................................................*/  
%covmerge (stblcovid=HLSMLSCV_STBLCOVID, stcovid=HLSMLSCF_STCOVID,new_var=LOSS_OF_SMELL);
/*Loss of taste..............................................................................................*/  
%covmerge (stblcovid=HLTSTSCV_STBLCOVID, stcovid=HLTSTSCF_STCOVID,new_var=LOSS_OF_TASTE);
/*Changes in vision, for example losing your vision, having blurred vision, or starting to see double..*/  
%covmerge (stblcovid=HVISNSCV_STBLCOVID, stcovid=HVISNSCF_STCOVID,new_var=VISION_CHANGES);
/*Speech difficulties, for example having trouble finding the words for something or stuttering........*/  
%covmerge (stblcovid=HSPCHSCV_STBLCOVID, stcovid=HSPCHSCF_STCOVID,new_var=SPEECH);
/*Numbness or tingling in arms, legs or toes.................................................................*/  
%covmerge (stblcovid=HNTNGSCV_STBLCOVID, stcovid=HNTNGSCF_STCOVID,new_var=NUMBNESS);
/*Was this on just one side of body?.........................................................................*/  
%covmerge (stblcovid=HNTOSSCV_STBLCOVID, stcovid=HNTOSSCF_STCOVID,new_var=NUMB_SIDE);
/*Tremors or involuntary muscle movements....................................................................*/  
%covmerge (stblcovid=HTIVMSCV_STBLCOVID, stcovid=HTIVMSCF_STCOVID,new_var=TREMORS);
/*Loss of balance, difficulty walking, or falls..............................................................*/  
%covmerge (stblcovid=HBLNCSCV_STBLCOVID, stcovid=HBLNCSCF_STCOVID,new_var=BALANCE);
/*Dizziness, sensation that the room is spinning, or feeling light-headed when you stand...............*/  
%covmerge (stblcovid=HDZYSCV_STBLCOVID, stcovid=HDZYSCF_STCOVID,new_var=DIZZINESS);
/*Problems with your memory..................................................................................*/  
%covmerge (stblcovid=HMEMSCV_STBLCOVID, stcovid=HMEMSCF_STCOVID,new_var=MEMORY);
/*Problems concentrating on things or feeling that you have "brain fog"......................................*/  
%covmerge (stblcovid=HBFOGSCV_STBLCOVID, stcovid=HBFOGSCF_STCOVID,new_var=CONCENTRATION);
/*Changes to your appetite...................................................................................*/  
%covmerge (stblcovid=HAPPTSCV_STBLCOVID, stcovid=HAPPTSCF_STCOVID,new_var=APPETITE);
/*Changes to your mood, for example feeling more anxious or depressed..................................*/  
%covmerge (stblcovid=HMOODSCV_STBLCOVID, stcovid=HMOODSCF_STCOVID,new_var=MOOD);
/*Insomnia (e.g., difficulty falling asleep or staying asleep)...............................................*/  
%covmerge (stblcovid=HINSMSCV_STBLCOVID, stcovid=HINSMSCF_STCOVID,new_var=INSOMNIA);
/*Hair loss..................................................................................................*/  
%covmerge (stblcovid=HHAIRSCV_STBLCOVID, stcovid=HHAIRSCF_STCOVID,new_var=HAIR_LOSS);
/*Seizures...................................................................................................*/  
%covmerge (stblcovid=HSEIZSCV_STBLCOVID, stcovid=HSEIZSCF_STCOVID,new_var=SEIZURES);
/*Other......................................................................................................*/  
%covmerge (stblcovid=HOTHRSCV_STBLCOVID, stcovid=HOTHRSCF_STCOVID,new_var=OTHER);


/*B.12.	Have you received any COVID-19 vaccines (PROMPT: IF THIS IS A FOLLOW UP VISIT SAY "since your last visit")?*/
%covmerge (stblcovid=RVACSCV_STBLCOVID, stcovid=RVACSCF_STCOVID,new_var=EVER_VACCINE);

length NUM_VACCINE $ 20; 
if RVACSCV_STBLCOVID=1 and RSD_SCV_STBLCOVID=1 then NUM_VACCINE="2 doses";
else if RVACSCV_STBLCOVID=1 then NUM_VACCINE="1 dose";
else if RVACSCV_STBLCOVID=0 then NUM_VACCINE="No dose";

if RVACSCF_STCOVID=0 then NUM_VACCINE="No dose"; 
else if NVACSCF_STCOVID=1 then NUM_VACCINE="1 dose";
else if NVACSCF_STCOVID=2 then NUM_VACCINE="2 doses";
else if NVACSCF_STCOVID=3 then NUM_VACCINE="3 doses";
else if NVACSCF_STCOVID=4 then NUM_VACCINE="More than 3 doses";

if NUM_VACCINE in ("1 dose","2 doses","3 doses","More than 3 doses") then VACCINATION=1;
else if NUM_VACCINE="No dose" then VACCINATION=0;

length education $ 30; 
if EDUCSSD_STBLSD in (1,2,3) then EDUCATION="Less than HS";
if EDUCSSD_STBLSD in (4) then EDUCATION="Completed HS";
if EDUCSSD_STBLSD in (5) then EDUCATION="Some College";
if EDUCSSD_STBLSD in (6) then EDUCATION="Completed 4 years of College";
if EDUCSSD_STBLSD in (7) then EDUCATION="Graduate School";
 
length marital_status $ 30; 
if MAR_SSD_STBLSD in (1) then marital_status="Married";
if MAR_SSD_STBLSD in (2,6) then marital_status="Not Married";
if MAR_SSD_STBLSD in (3,4,5) then marital_status="Widowed, Divorced, or Separated";
if MAR_SSD_STBLSD in (7) then marital_status="Other";

run;

*SOCIODEMOGRAPHICS;
proc freq data=STAR.STAR_bl_clean;
table HIVSSEL_STEL (
/*VISIT YEAR*/ EL_YEAR
/*RACE*/ RACE_CAT 
/*ETHNICITY*/ LTNXSEL_STEL 
/*EDUCATION*/ EDUCSSD_STBLSD EDUCATION 
/*EMP STATUS*/ EMPSTSSD_STBLSD 
/*MARITAL STATUS*/ MAR_SSD_STBLSD marital_status 
/*INCOME*/ INCMSSD_STBLSD 
/*ART USE*/ CTAAMSMH_STBLHH
/*COMORBIDIES*/
EPNEUMSMH_STBLHH EHBCLSMH_STBLHH MCBSSMH_STBLHH EHYTNSMH_STBLHH EVANSMH_STBLHH 
EVMISMH_STBLHH EVCFSMH_STBLHH EVSTSMH_STBLHH EVTISMH_STBLHH EBVBLKSMH_STBLHH
EVAFBSMH_STBLHH EVAFLSMH_STBLHH EHBPROSMH_STBLHH MCKPSMH_STBLHH ECOPDSMH_STBLHH
EASTHSMH_STBLHH EPFBSMH_STBLHH EPHYSMH_STBLHH EPEMSMH_STBLHH EDVTSMH_STBLHH
EPADPSMH_STBLHH ELNGSMH_STBLHH ESAPSMH_STBLHH LDFLSMH_STBLHH EDPRSMH_STBLHH
EANXSMH_STBLHH ESCHZSMH_STBLHH EPTSDSMH_STBLHH EBPDSMH_STBLHH ESUICSMH_STBLHH
EOPUDSMH_STBLHH
)
*HIVSSEL_STEL;
where HIVSSEL_STEL>0;
run;

*AGE;
proc univariate data=STAR.STAR_bl_clean;
class HIVSSEL_STEL;
var AGE;
histogram;
where HIVSSEL_STEL>0;
run;

*AGE;
proc univariate data=STAR.STAR_bl_clean;
var AGE;
histogram;
run;

*WEIGHT;
proc univariate data=STAR.STAR_bl_clean;
class HIVSSEL_STEL;
var WGHTSPE_STPE;
histogram;
where HIVSSEL_STEL>0 and WGHTSPE_STPE>0;
run;

*WEIGHT;
proc univariate data=STAR.STAR_bl_clean;
var WGHTSPE_STPE;
histogram;
where HIVSSEL_STEL>0 and WGHTSPE_STPE>0;
run;

*HEIGHT;
proc univariate data=STAR.STAR_bl_clean;
class HIVSSEL_STEL;
var HGHTSPE_STPE;
histogram;
where HIVSSEL_STEL>0 and HGHTSPE_STPE>0;
run;

*HEIGHT;
proc univariate data=STAR.STAR_bl_clean;
var HGHTSPE_STPE;
histogram;
where HIVSSEL_STEL>0 and HGHTSPE_STPE>0;
run;

*BMI;
proc univariate data=STAR.STAR_bl_clean;
class HIVSSEL_STEL;
var BMI;
histogram;
where HIVSSEL_STEL>0;
run;

*BMI;
proc univariate data=STAR.STAR_bl_clean;
var BMI;
histogram;
where HIVSSEL_STEL>0;
run;

*QUANTITATIVE CATEGORY; 
proc freq data=STAR.STAR_bl_clean;
table HRQNSLB_STLAB*HIVSSEL_STEL;
where HIVSSEL_STEL=1 and HRQNSLB_STLAB>0;
run;

*QUANTITATIVE HIV VL RESULT;
proc univariate data=STAR.STAR_bl_clean;
class HIVSSEL_STEL;
var HRQVSLB_STLAB ;
histogram;
where HIVSSEL_STEL=1 and HRQVSLB_STLAB>0;
run;

*COVID;
proc freq data=STAR.STAR_bl_clean;
table EVER_POS_COVID*HIVSSEL_STEL/ chisq;
where HIVSSEL_STEL>0 and EVER_POS_COVID>=0;
run;

*COVID RECOVERY;
proc freq data=STAR.STAR_bl_clean;
table COVID_RECOVERY*HIVSSEL_STEL/ chisq;
where HIVSSEL_STEL>0 and COVID_RECOVERY>=0;
run;

*VACCINES;
proc freq data=STAR.STAR_bl_clean;
table (NUM_VACCINE VACCINATION)*HIVSSEL_STEL/ chisq;
where HIVSSEL_STEL>0 and NUM_VACCINE~="";
run;

*SYMPTOMS;
proc freq data=STAR.STAR_bl_clean;
table (COVID_RECOVERY MUSCLE_ACHES FATIGUE HEADACHE LOSS_OF_SMELL LOSS_OF_TASTE VISION_CHANGES SPEECH NUMBNESS
TREMORS BALANCE DIZZINESS MEMORY CONCENTRATION APPETITE MOOD INSOMNIA HAIR_LOSS SEIZURES
)*HIVSSEL_STEL;
where HIVSSEL_STEL>0 and COVID_RECOVERY=0;
run;

*EXP;
proc freq data=STAR.STAR_bl_clean;
table 
/*HOSPITALIZATION STBLCOVID ONLY*/ HOSPCSCV_STBLCOVID
/*COVID COUNT STCOVID ONLY*/ EPOSSCF_STCOVID LVTPSCF_STCOVID NTTPSCF_STCOVID;
run;


***HOSP RECODE***

*TAB OF HOSPITALIZATIONS IN STCOVID;
proc freq data=STAR.stcovids1;
table STARID*HOSPCSCF_STCOVIDS1;
ods output CrossTabFreqs=test;
run;

data test1;
set test;
if HOSPCSCF_STCOVIDS1~=1 then DELETE;
if STARID=. then DELETE;
keep STARID HOSPCSCF_STCOVIDS1 Frequency;
rename Frequency=HOSP;
run;

data test2;
set STAR.STAR_bl_clean;
keep STARID VISIT HIVSSEL_STEL TPOSSCV_STBLCOVID HOSPCSCV_STBLCOVID EPOSSCF_STCOVID LVTPSCF_STCOVID NTTPSCF_STCOVID ; 
run;

proc sort data=test1;
by STARID;
proc sort data=test2;
by STARID;
run;

data test3;
merge test2 test1 ;
by STARID;
run;

data test3;
set test3;
if HOSP>0 or HOSPCSCV_STBLCOVID=1 then HOSPITALIZATION=1;
else if HOSP=0 or HOSPCSCV_STBLCOVID=0 then HOSPITALIZATION=0;
run;

proc freq data=test3;
table HOSPITALIZATION*HIVSSEL_STEL /chisq;
where HIVSSEL_STEL>0;
run;

****HEALTHCARE UTILIZATION****;

proc freq data=STAR.STAR_bl_clean;
table EVER_POS_COVID*HIVSSEL_STEL;
where HIVSSEL_STEL;
run;

proc freq data=STAR.STAR_bl_clean;
table (
HCP6SHC_STBLHCU		/*B.1.	Have you seen a health care provider in the past year?*/
)*EVER_POS_COVID /chisq;
where HIVSSEL_STEL=1 /*HIV POSITIVE*/ and EVER_POS_COVID>=0;
run;

*CHECKS;
/*proc print data=test3;*/
/*where EPOSSCF_STCOVID=1 or LVTPSCF_STCOVID=1;*/
/*run;*/

proc print data=STAR.STAR_bl_clean;
var STARID VISIT EPOSSCF_STCOVID LVTPSCF_STCOVID NTTPSCF_STCOVID;
where (EPOSSCF_STCOVID=1 or  LVTPSCF_STCOVID=1) and NTTPSCF_STCOVID<1 ;
run;

*****************
***EXPLORATORY***
*****************
;

proc freq data=STAR.STAR_bl noprint;
table STARID / out=STAR_bl_dup;
run;

data STAR_bl_dup;
set STAR_bl_dup;
if COUNT<2 then DELETE;
run;

proc print data=STAR.STAR_bl;
where STARID in (7310067,7410331);
run;

proc freq data=STAR.STBLOB;
table SKPPSOB PLE_SOB PLETSOB BPDSPSOB PREGSOB;
run;

proc freq data=STAR.STBLOB;
table EVPOCSOB*(SKPPSOB PLE_SOB PLETSOB BPDSPSOB PREGSOB);
where SITE=74;
run;

proc freq data=STAR.STBLOB;
table SKPPSOB;
where SKPPSOB=1;
run;

proc freq data=STAR.STCOVID;
table EPOSSCF*RVACSCF;
run;

data STBLOB_new;
set STAR.STBLOB;
else if SKPPSOB=1 or PLE_SOB=1 or BPDSPSOB=1 then IRR_MEN=1;
else IRR_MEN=0;
run;

*ALL SITES;
proc freq data=STBLOB_new;
table IRR_MEN;
run;

*MIAMI ONLY;
proc freq data=STBLOB_new;
table IRR_MEN;
where SITE=74 or SITE=73;
run;

data STAR.STAR_BL;
MERGE STAR.STEL(IN = a);
BY STARID;
RUN;

**********
***PREP***
**********
;
proc freq data=STAR.STAR_BL;
table ETPREPSMH_STBLHH*TPREPSMH_STBLHH;
run;

*********
***ART***
*********
;

data ART;
set STAR.stblhhs2;
keep STARID VISIT RXNOR2BSMH_STBLHHS2 MED;

MED=lowcase(RXNOR2BSMH_STBLHHS2);
run;

%macro seq(longdata,id,suffix);

proc sort data=&longdata;
by &id;
run;

data &longdata;
set &longdata;
by &id;
if first.&id then &suffix=1;
if &id = lag(&id) then &suffix+1;
run;

proc sort data=&longdata;
by &id &suffix;
run;

%mend;

%seq(ART,STARID,seq);


%macro towide(longdata,widedata,id,suffix,suffixlo,suffixhi,vars,types=,lengths=,numprint=,quiet=,sorted=);

  /* 
  longdata - name of input data file that is in long form
  widedata - name of output data file that will be in wide form
  id       - variable that uniquely identifies the wide records
  suffix   - variable name for the suffix of the wide variables
  suffixlo - the lowest value of the suffix variable
  suffixhi - the highest value of the suffix variable
  vars     - a list of the base names to transpose

  optional parameters
    types    - (default, all numeric) 
               A list of the types of the long variables separated by spaces.
               N for numeric and C for character.  
    lengths  - (default 8 for each var)
               a list of the lengths of the long variables separated by spaces.
    numprint - (default 10) 
               Number of wide records to print for verification
    quiet    - suppress PROC PRINT and PROC MEANS for verification
               NO (default) - display proc print and proc means
               YES - suppress display of proc print and proc means 
    sorted   - whether the input (long) data file is already sorted by id
               NO (default) - assumes longdata is not sorted and needs to
                              be sorted by id
               YES - assumes longdata is already sorted and does not sort
                     it again ;
  */

  %if &numprint =  %then %let numprint = 10 ;
  %if &quiet    =  %then %let quiet    = NO ;
  %let quiet = %upcase(&quiet) ;

  * count up how many variables in vars, store in VARNUM;
  %let varnum=%eval(1);
  %let varname = %scan(&vars,&varnum," ");
  %do %until (&varname = );
    %let varnum=%eval(&varnum + 1);
    %let varname = %scan(&vars,&varnum," ");
  %end;
  %let nvars = %eval(&varnum - 1);

  * get the last variable from the id, sore in LASTID ;
  %let idnum=%eval(1);
  %let idname = %scan(&id,&idnum," ");
  %do %until (&idname =  );
    %let idnum=%eval(&idnum + 1);
    %let idname = %scan(&id,&idnum," ");
  %end;
  %let nids = %eval(&idnum - 1);
  %let lastid = %scan(&id,&nids);

  %put ------------------------------------------------------------------ ;
  %put - Reshape Long to Wide: Actions to taken summarized below          ; 
  %put ------------------------------------------------------------------ ;
  %put - Input  (long) data file is                        : &longdata    ;
  %put - Output (wide) data file is                        : &widedata    ;
  %put - Variable that uniquely identifies wide records is : &id          ;  
  %put - Variable name with suffix for wide variable is    : &suffix      ;
  %put - and can range from : &suffixlo to &suffixhi ;
  %put - Long variables to wide variables... ;

  %if &sorted EQ YES %then %let infile = &longdata;
  %if &sorted NE YES %then 
  %do;
    %let infile = _123456_ ;
    proc sort data=&longdata out=_123456_ ;
      by &id ;
    run;
  %end;

  * start the data step.  Make widedata from longdata by id;
  data &widedata ;
    set &infile ;
    by &id ; 

    * make ARRAY, RETAIN and DROP for each variable in VARS ;
    * *********************************************;
    %do varnum = 1 %to &nvars ;
      %let varname = %scan(&vars   ,&varnum," ");
      %let vartype = %scan(&types  ,&varnum," ");
      %let varlen  = %scan(&lengths,&varnum," ");
      %if &vartype =   %then %let vartype = N;
      %if &varlen  =  %then %let varlen  = 8;
      %if &vartype = C %then %let dollar = $; %else %let dollar = ;

      array _array&varnum(&suffixlo:&suffixhi) 
            &dollar &varlen &varname&suffixlo - &varname&suffixhi ;
      retain &varname&suffixlo - &varname&suffixhi ;
      drop   &varname ;

      %put -  &varname  -> &varname&suffixlo ... &varname&suffixhi -> of type &vartype and length &varlen ;
    %end;
    * *********************************************;

    * if first record of group, then initialize all to . or " " ;
    if first.&lastid then
    do;
      do _i_ = &suffixlo to &suffixhi;

        * *********************************************;
        %do varnum = 1 %to &nvars ;
          %let varname = %scan(&vars,&varnum," ");
          %let vartype = %scan(&types  ,&varnum," ");
          %if &vartype =   %then %let vartype = N;
          %if &vartype = C %then %let dot = " "; %else %let dot = .;

          _array&varnum(_i_) = &dot ;
    
        %end;
        * *********************************************;
      end;
    end;

    * store wide variable into narrow variable ;
    * *********************************************;
    %do varnum = 1 %to &nvars ;
      %let varname = %scan(&vars,&varnum," ");

      _array&varnum(&suffix) = &varname ;

    %end;
    * *********************************************;

    * if last variable of group, output the record ;
    if last.&lastid then output ;

    * drop _i_ and suffix variable ;
    drop _i_ &suffix ;

  run;


  %if &quiet NE YES %then
  %do;

    title1 "1A. Verify reshaping of long to wide using PROC PRINT of &numprint wide records.";
    title2 "    Compare this print of the long data below (&longdata) with the "        ; 
    title3 "    PROC PRINT of the wide data (&widedata) in step 1B below."   ;
    title5 "PROC PRINT of LONG data file &longdata";
    proc print data=&longdata(obs= %eval(&numprint*(&suffixhi-&suffixlo+1))  );
      var &id &suffix &vars ;
    run;


    title1 "1B. Verify reshaping of long to wide using PROC PRINT of &numprint wide records";
    title2 "    Compare this print of the wide data (&widedata) below with the "        ; 
    title3 "    PROC PRINT of the long data (&longdata) in Step 1A above"   ;
    title5 "PROC PRINT of WIDE data file &widedata";
    proc print data=&widedata(obs=&numprint);
      var &id 
      %do varnum = 1 %to &nvars ;
        %let varname = %scan(&vars,&varnum," ");
        &varname&suffixlo - &varname&suffixhi
      %end;
      ;
    run;

    title1 "2A. Verify reshaping of long to wide using PROC MEANS";
    title2 "    Compare this PROC MEANS for the long data (&longdata) with the "        ; 
    title3 "    PROC MEANS of the wide data (&widedata) in step 2B below"   ;
    title5 "PROC MEANS of LONG data file &longdata";
    proc means data=&longdata;
      class  &suffix;
      var 
      %do varnum = 1 %to &nvars ;
        %let varname = %scan(&vars,&varnum," ");
        %let vartype = %scan(&types  ,&varnum," ");
        %if &vartype NE C %then &varname ;
      %end;
      ;
    run;

    title1 "2B. Verify reshaping of long to wide using PROC MEANS";
    title2 "    Compare this PROC MEANS for the wide data (&widedata) below" ;
    title3 "    with the PROC MEANS of the long data (&longdata) in step 2A above"    ;
    title5 "PROC MEANS of WIDE data file &widedata";
    proc means data=&widedata;
      var 
      %do j = &suffixlo %to &suffixhi ;
        %do varnum = 1 %to &nvars ;
          %let varname = %scan(&vars,&varnum," ");
          %let vartype = %scan(&types  ,&varnum," ");
          %if &vartype NE C %then &varname&j ;
        %end;
      %end;
      ;
    run;
  %end;

%mend towide;

/*
%macro towide(longdata,widedata,id,suffix,suffixlo,suffixhi,vars,types=,lengths=,numprint=,quiet=,sorted=);

  longdata - name of input data file that is in long form
  widedata - name of output data file that will be in wide form
  id       - variable that uniquely identifies the wide records
  suffix   - variable name for the suffix of the wide variables
  suffixlo - the lowest value of the suffix variable
  suffixhi - the highest value of the suffix variable
  vars     - a list of the base names to transpose
*/

%towide(ART,ART_w,starid,seq,1,4,MED,types=C,lengths=20);


data STAR_bl_ART;
merge STAR.STAR_bl (in=a) ART_w;
by STARID;
if a=1;
run;

proc freq data=ART_w;
table med1;
run;

*HIV+ only;
proc freq data=STAR_bl_ART;
table med1 / plot=FreqPlot;;
where HIVSSMH_STBLHH=1;
run;

*HIV+ and pregnant;
proc freq data=STAR_bl_ART;
table med1 / plot=FreqPlot;;
where HIVSSMH_STBLHH=1 and PREGSOB_STBLOB=1;
run;

proc freq data=STAR_bl_ART;
table HIVSSEL_STEL HIVSSMH_STBLHH PREGSOB_STBLOB;
run;

proc print data=STAR_bl_ART;
var STARID VISIT HIVSSEL_STEL HIVSSMH_STBLHH CTAAMSMH_STBLHH MED1--MED4;
where HIVSSEL_STEL=2 and MED1~="";
run;

proc print data=STAR_bl_ART;
var STARID VISIT HIVSSEL_STEL HIVSSMH_STBLHH CTAAMSMH_STBLHH MED1--MED4;
where HIVSSEL_STEL=2 and MED1~="";
run;

********************
***EMILY KATZ R01***
********************
;
proc freq data=STAR_bl_ART;
table MCBSSMH_STBLHH;
run;

data STAR_bl_ART;
set STAR_bl_ART;

if WGHTSPE_STPE>0 and HGHTSPE_STPE>0 then do;
BMI=WGHTSPE_STPE/((HGHTSPE_STPE/100)**2);
end;
else BMI=.;

run;

proc print data=STAR_bl_ART;
var starid;
where (RCAASEL_STEL=1 or LTNXSEL_STEL=1) and MCBSSMH_STBLHH=0 and BMI>=30 and site=74 and PREGSOB_STBLOB=0;
run;

**********
***STIS***
**********
;
proc freq data=STAR.STAR_bl;
table (CURRSLB_STLAB CRSRSLB_STLAB CORRSLB_STLAB /*CHLAMYDIA*/ 
GURRSLB_STLAB GRSRSLB_STLAB GORRSLB_STLAB /*GONORRHEA*/
TURRSLB_STLAB /*TRICH*/
RRPRSLB_STLAB RTRESLB_STLAB RFTASLB_STLAB RMHASLB_STLAB)*HIVSSEL_STEL /*SYPHILIS*/;
run;

proc univariate data=STAR.STAR_bl plot;
var TIRPRSLB_STLAB;
where RRPRSLB_STLAB=1 and TIRPRSLB_STLAB>=0;
run;
